import { useState, useEffect, useRef, useCallback } from 'react'
import {
  getCachedStudyTools,
  getCachedNotes,
  saveNotes as dbSaveNotes,
  appendSessionRecall,
} from '../lib/db'
import { getAccessToken } from '../lib/supabase'
import { useCelebration } from '../utils/useCelebration'
import AIChatView from './AIChatView'

function fmt(seconds) {
  const m = Math.floor(seconds / 60).toString().padStart(2, '0')
  const s = (seconds % 60).toString().padStart(2, '0')
  return `${m}:${s}`
}

function wordCount(text) {
  return text.trim() ? text.trim().split(/\s+/).length : 0
}

function loadStudyTools(courseId) {
  const data = getCachedStudyTools()
  return data?.courseIdx === courseId ? data : null
}

function saveNotes(courseId, dateStr, notes) {
  dbSaveNotes(courseId, dateStr, notes)
}

function loadNotes(courseId, dateStr) {
  return getCachedNotes(courseId, dateStr)
}

function appendRecall(courseId, courseName, sessionType, text) {
  appendSessionRecall({ courseId, courseName, sessionType, text, timestamp: Date.now() })
}

async function loadJsPDF() {
  if (window.jspdf?.jsPDF) return window.jspdf.jsPDF
  return new Promise((resolve, reject) => {
    const s = document.createElement('script')
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'
    s.onload = () => resolve(window.jspdf.jsPDF)
    s.onerror = () => reject(new Error('Failed to load jsPDF'))
    document.head.appendChild(s)
  })
}

async function generatePDF({ courseName, dateStr, sessionType, recallText, concepts, main, summary }) {
  const JsPDF = await loadJsPDF()
  const doc = new JsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = 210
  const margin = 18
  const contentW = pageW - margin * 2
  let y = 20

  const addText = (text, x, size, color, bold) => {
    doc.setFontSize(size)
    doc.setTextColor(...color)
    if (bold) doc.setFont('helvetica', 'bold')
    else doc.setFont('helvetica', 'normal')
    doc.text(text, x, y)
  }

  const addWrapped = (text, x, size, color, maxW) => {
    doc.setFontSize(size)
    doc.setTextColor(...color)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(text, maxW)
    doc.text(lines, x, y)
    y += lines.length * (size * 0.4 + 1)
  }

  const section = (title) => {
    y += 4
    doc.setFillColor(245, 247, 252)
    doc.roundedRect(margin, y - 5, contentW, 9, 2, 2, 'F')
    doc.setFontSize(10)
    doc.setTextColor(80, 80, 120)
    doc.setFont('helvetica', 'bold')
    doc.text(title, margin + 4, y + 1)
    y += 8
  }

  // ── Header ──
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, pageW, 14, 'F')
  doc.setFontSize(12)
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.text('StudyEdge Session Notes', margin, 9)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`${dateStr}`, pageW - margin, 9, { align: 'right' })
  y = 24

  addText(`${courseName}`, margin, 18, [20, 20, 40], true)
  y += 9
  addText(`${sessionType} Session`, margin, 11, [100, 100, 130], false)
  y += 8
  doc.setDrawColor(220, 220, 235)
  doc.line(margin, y, pageW - margin, y)
  y += 8

  // ── Sections ──
  if (recallText?.trim()) {
    section('Active Recall')
    addWrapped(recallText.trim(), margin, 10, [40, 40, 60], contentW)
    y += 4
  }

  if (concepts?.trim()) {
    section('Key Concepts')
    addWrapped(concepts.trim(), margin, 10, [40, 40, 60], contentW)
    y += 4
  }

  if (main?.trim()) {
    section('Session Notes')
    addWrapped(main.trim(), margin, 10, [40, 40, 60], contentW)
    y += 4
  }

  if (summary?.trim()) {
    section('Summary')
    addWrapped(summary.trim(), margin, 10, [40, 40, 60], contentW)
    y += 4
  }

  // ── Footer ──
  const pageH = 297
  doc.setFontSize(8)
  doc.setTextColor(160, 160, 180)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by StudyEdge • studyedge.app', pageW / 2, pageH - 8, { align: 'center' })

  const filename = `StudyEdge_${courseName.replace(/\s+/g, '_')}_${dateStr}.pdf`
  doc.save(filename)
}

const ENCOURAGE = [
  'Great session! Every minute you put in compounds into exam-day confidence.',
  'Solid work. Consistent sessions like this are what separate top performers.',
  "You showed up and did the work. That's what matters most.",
  'Another session in the books. Your future self thanks you.',
]

const ACTIVITY_COLORS = {
  'review':            '#3B82F6',
  'active-recall':     '#A855F7',
  'flashcards':        '#EC4899',
  'practice-problems': '#F97316',
  'summary':           '#14B8A6',
  'break':             '#22C55E',
}

export default function FocusMode({ session, blueprint, onComplete, onExit, nextSession, onStartNext, onGoToTools, course, onShowPaywall, userId }) {
  const totalSec = session.duration * 60
  const isLongSession = session.duration > 45
  const todayStr = new Date().toISOString().split('T')[0]

  // ── Blueprint blocks ──
  const blocks = blueprint?.blocks ?? null
  const [blockIdx, setBlockIdx] = useState(0)
  const [blockRemaining, setBlockRemaining] = useState(() => blocks ? blocks[0].duration * 60 : totalSec)
  const [completedBlocks, setCompletedBlocks] = useState(new Set())
  const [blockTransition, setBlockTransition] = useState(null) // { title, nextTitle, nextInstruction }
  const blockAdvanceRef = useRef(null)

  const currentBlock = blocks ? blocks[blockIdx] : null
  const nextBlock = blocks ? blocks[blockIdx + 1] : null
  const blockColor = currentBlock ? (ACTIVITY_COLORS[currentBlock.activity] ?? session.color.dot) : session.color.dot
  const blockPct = currentBlock ? (1 - blockRemaining / (currentBlock.duration * 60)) : 0

  // ── Timer ──
  const [remaining, setRemaining] = useState(totalSec)
  const [running, setRunning] = useState(true)
  const [finished, setFinished] = useState(false)
  const intervalRef = useRef(null)

  // ── Tabs ──
  const [activeTab, setActiveTab] = useState('recall')
  const [tabsVisited, setTabsVisited] = useState(new Set(['recall']))

  // ── Completion ──
  const [showComplete, setShowComplete] = useState(false)
  const [encourageMsg] = useState(() => blueprint?.successNote ?? ENCOURAGE[Math.floor(Math.random() * ENCOURAGE.length)])
  const celebrate = useCelebration()
  const celebratedRef = useRef(false)
  useEffect(() => {
    if (showComplete && !celebratedRef.current) {
      celebratedRef.current = true
      celebrate('big')
    }
  }, [showComplete])
  const [pdfDownloading, setPdfDownloading] = useState(false)

  // ── Pomodoro ──
  const BREAK_INTERVAL = 25 * 60
  const BREAK_DURATION = 5 * 60
  const [breakBanner, setBreakBanner] = useState(false)
  const [breakOverlay, setBreakOverlay] = useState(false)
  const [breakRemaining, setBreakRemaining] = useState(BREAK_DURATION)
  const lastBreakCount = useRef(0)

  // ── Study tools ──
  const [studyTools] = useState(() => loadStudyTools(session.courseId))
  const [inSessionFlashcards, setInSessionFlashcards] = useState(null)
  const [fcGenerating, setFcGenerating] = useState(false)
  const [fcGenerateError, setFcGenerateError] = useState('')
  const flashcards = inSessionFlashcards ?? studyTools?.flashcards ?? []

  // ── Active Recall ──
  const [recallText, setRecallText] = useState('')
  const [recallSaved, setRecallSaved] = useState(false)
  const [showRecallCards, setShowRecallCards] = useState(false)
  const [rcIdx, setRcIdx] = useState(0)
  const [rcFlipped, setRcFlipped] = useState(false)
  const [recallWritingTimer, setRecallWritingTimer] = useState(0)
  const recallTimerRef = useRef(null)
  const recallStartedRef = useRef(false)
  const lastTypedRef = useRef(0)
  const [checkPulse, setCheckPulse] = useState(false)

  // ── Flashcards ──
  const [fcIdx, setFcIdx] = useState(0)
  const [fcFlipped, setFcFlipped] = useState(false)
  const [fcKnown, setFcKnown] = useState(new Set())
  const [fcAnswerState, setFcAnswerState] = useState(null) // 'correct' | 'wrong' | null

  // ── Quick Quiz ──
  const [quizQuestions, setQuizQuestions] = useState(null)
  const [quizLoading, setQuizLoading] = useState(false)
  const [quizError, setQuizError] = useState('')
  const [quizIdx, setQuizIdx] = useState(0)
  const [quizAnswers, setQuizAnswers] = useState([])
  const [quizSelected, setQuizSelected] = useState(null)
  const [quizConfirmed, setQuizConfirmed] = useState(false)
  const [quizDone, setQuizDone] = useState(false)
  const [quizAnswerFlash, setQuizAnswerFlash] = useState(null) // 'correct' | 'wrong'

  // ── Notes ──
  const [notesConcepts, setNotesConcepts] = useState('')
  const [notesMain, setNotesMain] = useState('')
  const [notesSummary, setNotesSummary] = useState('')
  const [notesSaved, setNotesSaved] = useState(false)
  const [notesAutoSaved, setNotesAutoSaved] = useState(false)
  const notesSaveRef = useRef(null)
  const conceptsRef = useRef(null)
  const mainRef = useRef(null)
  const summaryRef = useRef(null)

  // ── Load saved notes ──
  useEffect(() => {
    const saved = loadNotes(session.courseId, todayStr)
    if (saved) {
      setNotesConcepts(saved.concepts ?? '')
      setNotesMain(saved.main ?? '')
      setNotesSummary(saved.summary ?? '')
    }
  }, [])

  // ── Auto-resize textareas after load ──
  useEffect(() => {
    [conceptsRef, mainRef, summaryRef].forEach(r => {
      if (r.current) { r.current.style.height = 'auto'; r.current.style.height = r.current.scrollHeight + 'px' }
    })
  }, [notesConcepts, notesMain, notesSummary])

  // ── Timer countdown ──
  useEffect(() => {
    if (!running || finished) return
    intervalRef.current = setInterval(() => {
      // Overall timer
      setRemaining(r => {
        if (r <= 1) { clearInterval(intervalRef.current); setRunning(false); setFinished(true); return 0 }
        return r - 1
      })
      // Block timer
      if (blocks) {
        setBlockRemaining(r => {
          if (r <= 1) return 0
          return r - 1
        })
      }
    }, 1000)
    return () => clearInterval(intervalRef.current)
  }, [running, finished, blocks])

  // ── Block advance when block timer hits 0 ──
  useEffect(() => {
    if (!blocks || blockRemaining > 0 || finished) return
    const current = blocks[blockIdx]
    const next = blocks[blockIdx + 1]
    // Mark block complete
    setCompletedBlocks(prev => new Set([...prev, blockIdx]))
    if (!next) return // last block; overall timer will handle finish

    // Show transition banner
    setBlockTransition({ title: current.title, nextTitle: next.title, nextInstruction: next.instruction })
    setRunning(false)

    blockAdvanceRef.current = setTimeout(() => {
      setBlockIdx(i => i + 1)
      setBlockRemaining(next.duration * 60)
      setBlockTransition(null)
      setRunning(true)
    }, 4000)

    return () => clearTimeout(blockAdvanceRef.current)
  }, [blockRemaining])

  // ── Auto-show complete ──
  useEffect(() => {
    if (finished) { const t = setTimeout(() => setShowComplete(true), 1200); return () => clearTimeout(t) }
  }, [finished])

  // ── Pomodoro banner ──
  useEffect(() => {
    if (!isLongSession || !running || finished) return
    const elapsed = totalSec - remaining
    const count = Math.floor(elapsed / BREAK_INTERVAL)
    if (count > lastBreakCount.current) { lastBreakCount.current = count; setBreakBanner(true) }
  }, [remaining])

  // ── Break countdown ──
  useEffect(() => {
    if (!breakOverlay) return
    setBreakRemaining(BREAK_DURATION)
    const t = setInterval(() => {
      setBreakRemaining(r => {
        if (r <= 1) { clearInterval(t); setBreakOverlay(false); setBreakBanner(false); return BREAK_DURATION }
        return r - 1
      })
    }, 1000)
    return () => clearInterval(t)
  }, [breakOverlay])

  // ── Recall writing timer ──
  useEffect(() => {
    if (recallText && !recallStartedRef.current) {
      recallStartedRef.current = true
      recallTimerRef.current = setInterval(() => setRecallWritingTimer(t => t + 1), 1000)
    }
    if (recallText) lastTypedRef.current = Date.now()
    return () => {}
  }, [recallText])

  useEffect(() => () => clearInterval(recallTimerRef.current), [])

  // ── Check Yourself pulse after 3 min inactivity ──
  useEffect(() => {
    if (!recallText || showRecallCards) return
    const check = setInterval(() => {
      if (Date.now() - lastTypedRef.current > 180000) setCheckPulse(true)
      else setCheckPulse(false)
    }, 10000)
    return () => clearInterval(check)
  }, [recallText, showRecallCards])

  // ── Notes auto-save ──
  useEffect(() => {
    clearTimeout(notesSaveRef.current)
    if (!notesConcepts && !notesMain && !notesSummary) return
    notesSaveRef.current = setTimeout(() => {
      saveNotes(session.courseId, todayStr, { concepts: notesConcepts, main: notesMain, summary: notesSummary })
      setNotesAutoSaved(true)
      setTimeout(() => setNotesAutoSaved(false), 2000)
    }, 2000)
    return () => clearTimeout(notesSaveRef.current)
  }, [notesConcepts, notesMain, notesSummary])

  // ── Escape key ──
  useEffect(() => {
    const handler = e => { if (e.key === 'Escape' && !showComplete) onExit() }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [onExit, showComplete])

  // ── Derived ──
  const elapsed = totalSec - remaining
  const pct = blocks ? blockPct : (totalSec > 0 ? elapsed / totalSec : 0)
  const strokeColor = finished ? '#10B981' : (blocks ? blockColor : session.color.dot)
  const R = 78
  const CIRC = 2 * Math.PI * R
  const dot = session.color.dot
  const hasNotes = !!(notesConcepts.trim() || notesMain.trim() || notesSummary.trim() || recallText.trim())

  // ── Handlers ──
  const visitTab = tab => { setActiveTab(tab); setTabsVisited(prev => new Set([...prev, tab])) }
  const handleMarkComplete = () => { if (running) setRunning(false); setShowComplete(true) }

  const handleSkipBlock = () => {
    if (!blocks || !nextBlock) return
    clearTimeout(blockAdvanceRef.current)
    setCompletedBlocks(prev => new Set([...prev, blockIdx]))
    setBlockTransition(null)
    setBlockIdx(i => i + 1)
    setBlockRemaining(nextBlock.duration * 60)
    setRunning(true)
  }
  const handleBackToDashboard = () => onComplete(session.id, elapsed)
  const handleStartNext = () => { if (nextSession && onStartNext) onStartNext(session.id, elapsed, nextSession); else onComplete(session.id, elapsed) }

  const handleCheckYourself = () => {
    if (recallText.trim()) appendRecall(session.courseId, session.courseName, session.sessionType, recallText)
    setRecallSaved(true); setShowRecallCards(true); setRcIdx(0); setRcFlipped(false)
  }

  const handleGenerateQuiz = async () => {
    setQuizLoading(true); setQuizError(''); setQuizQuestions(null)
    setQuizAnswers([]); setQuizIdx(0); setQuizSelected(null); setQuizConfirmed(false); setQuizDone(false)
    try {
      const token = await getAccessToken()
      const res = await fetch('/api/generate-study-tools', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({
          mode: 'quick-quiz',
          courseName: session.courseName,
          sessionType: session.sessionType,
          text: [
            notesConcepts && `Key concepts:\n${notesConcepts}`,
            notesMain && `Notes:\n${notesMain}`,
            notesSummary && `Summary:\n${notesSummary}`,
            studyTools?.text?.slice(0, 3000),
          ].filter(Boolean).join('\n\n') || '',
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error ?? 'Quiz generation failed')
      setQuizQuestions(data.questions)
    } catch (e) { setQuizError(e.message) }
    finally { setQuizLoading(false) }
  }

  const handleConfirmAnswer = () => {
    if (quizSelected === null) return
    const q = quizQuestions[quizIdx]
    const correct = quizSelected === q.answer
    setQuizAnswers(prev => [...prev, { selected: quizSelected, correct, question: q }])
    setQuizConfirmed(true)
    setQuizAnswerFlash(correct ? 'correct' : 'wrong')
    setTimeout(() => setQuizAnswerFlash(null), 600)
  }

  const handleNextQuestion = () => {
    if (quizIdx + 1 >= quizQuestions.length) setQuizDone(true)
    else { setQuizIdx(i => i + 1); setQuizSelected(null); setQuizConfirmed(false) }
  }

  const resetQuiz = () => { setQuizQuestions(null); setQuizDone(false); setQuizAnswers([]); setQuizIdx(0); setQuizSelected(null); setQuizConfirmed(false) }

  const handleGenerateFlashcards = async () => {
    const sessionNotes = [
      notesConcepts && `Key concepts:\n${notesConcepts}`,
      notesMain && `Notes:\n${notesMain}`,
      notesSummary && `Summary:\n${notesSummary}`,
    ].filter(Boolean).join('\n\n')
    const text = [sessionNotes, studyTools?.text?.slice(0, 4000)].filter(Boolean).join('\n\n')
    if (text.length < 50) { setFcGenerateError('Add some notes in the Notes tab first to generate flashcards.'); return }
    setFcGenerating(true); setFcGenerateError('')
    try {
      const token = await getAccessToken()
      const res = await fetch('/api/generate-study-tools', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ text }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error ?? 'Failed to generate flashcards')
      setInSessionFlashcards(data.flashcards ?? [])
      setFcIdx(0); setFcFlipped(false); setFcKnown(new Set())
    } catch (e) { setFcGenerateError(e.message) }
    finally { setFcGenerating(false) }
  }

  const handleSaveNotes = () => {
    saveNotes(session.courseId, todayStr, { concepts: notesConcepts, main: notesMain, summary: notesSummary })
    setNotesSaved(true); setTimeout(() => setNotesSaved(false), 2000)
  }

  const handleDownloadPDF = async () => {
    setPdfDownloading(true)
    try {
      await generatePDF({
        courseName: session.courseName, dateStr: todayStr, sessionType: session.sessionType,
        recallText, concepts: notesConcepts, main: notesMain, summary: notesSummary,
      })
    } catch (e) { console.error('PDF error:', e) }
    finally { setPdfDownloading(false) }
  }

  const autoGrow = e => { e.target.style.height = 'auto'; e.target.style.height = e.target.scrollHeight + 'px' }

  // ─── RENDER ─────────────────────────────────────────────────────────────────
  return (
    <div className="fixed inset-0 z-[100] flex flex-col overflow-hidden bg-slate-50 dark:bg-[#070D1A]">
      {/* Top accent line */}
      <div className="h-0.5 w-full shrink-0" style={{ backgroundColor: dot }} />

      {/* Background glow */}
      <div className="absolute inset-0 pointer-events-none" style={{ background: `radial-gradient(ellipse 80% 40% at 50% 0%, ${dot}14 0%, transparent 65%)` }} />

      {/* ── Pomodoro break banner ── */}
      {breakBanner && !breakOverlay && (
        <div className="relative z-10 flex items-center gap-3 px-4 py-2.5 shrink-0" style={{ backgroundColor: `${dot}18`, borderBottom: `1px solid ${dot}28` }}>
          <div className="w-2 h-2 rounded-full shrink-0 animate-pulse" style={{ backgroundColor: dot }} />
          <span className="text-slate-300 text-xs">5-minute break recommended — you've been studying for 25 minutes</span>
          <div className="ml-auto flex items-center gap-2 shrink-0">
            <button onClick={() => setBreakOverlay(true)} className="text-xs px-3 py-1 rounded-lg font-medium text-white" style={{ backgroundColor: dot }}>Take Break</button>
            <button onClick={() => setBreakBanner(false)} className="text-xs text-slate-500 hover:text-slate-300 transition-colors">Dismiss</button>
          </div>
        </div>
      )}

      {/* ── Break overlay ── */}
      {breakOverlay && (
        <div className="absolute inset-0 z-[110] flex flex-col items-center justify-center bg-slate-50 dark:bg-[#070D1A]">
          <div className="text-center">
            <div className="relative flex items-center justify-center mb-10">
              <div className="w-36 h-36 rounded-full" style={{ backgroundColor: dot, opacity: 0.15, animation: 'breathe 4s ease-in-out infinite' }} />
              <div className="absolute w-24 h-24 rounded-full" style={{ backgroundColor: dot, opacity: 0.3, animation: 'breathe 4s ease-in-out infinite 0.8s' }} />
              <div className="absolute w-12 h-12 rounded-full" style={{ backgroundColor: dot }} />
            </div>
            <h2 className="text-3xl font-bold text-white mb-2">Take a breath</h2>
            <p className="text-slate-400 text-sm mb-3">Inhale 4s &nbsp;·&nbsp; Hold 4s &nbsp;·&nbsp; Exhale 4s</p>
            <p className="text-5xl font-mono font-bold mb-8" style={{ color: dot }}>{fmt(breakRemaining)}</p>
            <button onClick={() => { setBreakOverlay(false); setBreakBanner(false) }} className="text-slate-500 hover:text-slate-300 text-sm transition-colors">Skip break, keep studying</button>
          </div>
        </div>
      )}

      {/* ── Session complete screen ── */}
      {showComplete && (
        <div className="absolute inset-0 z-[105] flex flex-col items-center justify-center px-6 overflow-y-auto py-10 bg-slate-50 dark:bg-[#070D1A]">
          <div className="w-full max-w-md">
            <div className="flex items-center justify-center mb-6">
              <div className="w-20 h-20 rounded-full flex items-center justify-center" style={{ backgroundColor: `${dot}20`, border: `2px solid ${dot}50`, boxShadow: `0 0 40px ${dot}30` }}>
                <svg className="w-10 h-10" style={{ color: dot }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                </svg>
              </div>
            </div>
            <h2 className="text-3xl font-bold text-white text-center mb-2">Session Complete</h2>
            <p className="text-slate-400 text-center text-sm mb-8 leading-relaxed">{encourageMsg}</p>

            <div className="grid grid-cols-2 gap-3 mb-4">
              <div className="bg-white dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/60 rounded-2xl p-4 text-center">
                <p className="text-2xl font-bold text-slate-900 dark:text-white font-mono">{fmt(Math.max(elapsed, 1))}</p>
                <p className="text-xs text-slate-500 mt-1">Time studied</p>
              </div>
              <div className="bg-white dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700/60 rounded-2xl p-4 text-center">
                <p className="text-2xl font-bold text-white">{tabsVisited.size}</p>
                <p className="text-xs text-slate-500 mt-1">Activities used</p>
              </div>
            </div>

            <div className="bg-slate-800/40 border border-slate-700/40 rounded-2xl p-4 mb-4">
              <p className="text-xs text-slate-600 mb-3 uppercase tracking-widest font-medium">Activities</p>
              {[
                { id: 'recall', label: 'Active Recall' },
                { id: 'flashcards', label: 'Flashcards' },
                { id: 'quiz', label: 'Quick Quiz' },
                { id: 'notes', label: 'Notes' },
              ].map(({ id, label }) => (
                <div key={id} className="flex items-center gap-3 py-1.5">
                  <span className="text-base">{tabsVisited.has(id) ? '✅' : '⬜'}</span>
                  <span className={`text-sm ${tabsVisited.has(id) ? 'text-slate-200' : 'text-slate-600'}`}>{label}</span>
                </div>
              ))}
            </div>

            {hasNotes && (
              <button
                onClick={handleDownloadPDF}
                disabled={pdfDownloading}
                className="w-full py-3 rounded-xl text-sm font-medium text-slate-300 bg-slate-800/80 border border-slate-700 hover:bg-slate-700/80 transition-colors mb-3 flex items-center justify-center gap-2"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                {pdfDownloading ? 'Generating PDF…' : 'Download Session Notes'}
              </button>
            )}

            <div className="flex flex-col gap-3">
              {nextSession && (
                <button onClick={handleStartNext} className="w-full py-4 rounded-2xl font-bold text-white text-base transition-all" style={{ backgroundColor: dot, boxShadow: `0 0 28px ${dot}40` }}>
                  Start Next — {nextSession.courseName}
                </button>
              )}
              <button onClick={handleBackToDashboard} className="w-full py-3.5 rounded-2xl font-semibold text-slate-600 dark:text-slate-300 bg-slate-100 dark:bg-slate-800/80 hover:bg-slate-200 dark:hover:bg-slate-700/80 border border-slate-200 dark:border-slate-700 transition-colors">
                Back to Dashboard
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Main session layout ── */}
      <div className="relative flex flex-col h-full overflow-hidden">

        {/* Top bar */}
        <div className="flex items-center justify-between px-5 py-3 shrink-0">
          <div className="flex items-center gap-3 min-w-0">
            <div className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: dot, boxShadow: `0 0 8px ${dot}80` }} />
            <span className="text-white font-bold text-base truncate">{session.courseName}</span>
            <span className="text-slate-700 shrink-0">·</span>
            <span className="text-slate-400 text-sm shrink-0 font-medium">{session.sessionType}</span>
          </div>
          <button onClick={onExit} className="text-slate-600 hover:text-slate-300 transition-colors flex items-center gap-1.5 text-sm shrink-0 ml-4">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
            Exit
          </button>
        </div>

        {/* Timer section */}
        <div className="flex flex-col items-center px-4 pb-2 shrink-0">
          {/* Block label */}
          {blocks && currentBlock && !finished && (
            <p className="text-xs font-bold uppercase tracking-widest mb-2 transition-colors" style={{ color: blockColor }}>
              Block {blockIdx + 1} of {blocks.length} — {currentBlock.title}
            </p>
          )}
          <div className="flex items-center justify-center gap-10 w-full">
          {/* Progress ring */}
          <div className="relative flex items-center justify-center">
            <svg width="190" height="190" className="-rotate-90" style={{ filter: `drop-shadow(0 0 ${running ? '20px' : '8px'} ${strokeColor}${running ? '60' : '30'})` }}>
              <circle cx="95" cy="95" r={R} fill="none" stroke="#111827" strokeWidth="8" />
              {/* Glow track */}
              <circle
                cx="95" cy="95" r={R}
                fill="none"
                stroke={strokeColor}
                strokeWidth="3"
                strokeDasharray={CIRC}
                strokeDashoffset={CIRC * (1 - pct)}
                opacity="0.25"
                style={{ filter: `blur(4px)`, transition: 'stroke-dashoffset 1s linear' }}
              />
              {/* Main ring */}
              <circle
                cx="95" cy="95" r={R}
                fill="none"
                stroke={strokeColor}
                strokeWidth="8"
                strokeLinecap="round"
                strokeDasharray={CIRC}
                strokeDashoffset={CIRC * (1 - pct)}
                style={{ transition: 'stroke-dashoffset 1s linear, stroke 0.5s', animation: running && !finished ? 'ringPulse 3s ease-in-out infinite' : 'none' }}
              />
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              {finished ? (
                <svg className="w-9 h-9 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                </svg>
              ) : (
                <>
                  <span className="font-mono font-bold tabular-nums leading-none" style={{ fontSize: '2.2rem', color: running ? 'white' : '#94a3b8' }}>
                    {fmt(blocks ? blockRemaining : remaining)}
                  </span>
                  <span className="text-xs mt-1 font-medium" style={{ color: running ? `${strokeColor}cc` : '#475569' }}>{running ? (blocks ? 'this block' : 'remaining') : 'paused'}</span>
                </>
              )}
            </div>
          </div>

          {/* Controls */}
          <div className="flex flex-col gap-3">
            <p className="text-slate-600 text-xs text-center">{session.duration} min session</p>
            {!finished && (
              <button
                onClick={() => setRunning(r => !r)}
                className="flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl font-medium text-slate-600 dark:text-slate-300 bg-slate-100 dark:bg-slate-800/80 hover:bg-slate-200 dark:hover:bg-slate-700/80 border border-slate-200 dark:border-slate-700 transition-colors text-sm"
              >
                {running
                  ? <><svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zM7 8a1 1 0 012 0v4a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v4a1 1 0 102 0V8a1 1 0 00-1-1z" clipRule="evenodd" /></svg>Pause</>
                  : <><svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clipRule="evenodd" /></svg>Resume</>
                }
              </button>
            )}
            {blocks && nextBlock && !finished && (
              <button
                onClick={handleSkipBlock}
                className="flex items-center justify-center gap-1.5 px-5 py-2 rounded-xl text-xs font-medium text-slate-500 hover:text-slate-300 bg-slate-800/50 border border-slate-800 hover:border-slate-700 transition-colors"
              >
                Skip Block
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
              </button>
            )}
            <button
              onClick={handleMarkComplete}
              className="flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl font-bold text-white text-sm transition-all"
              style={{ backgroundColor: finished ? '#10B981' : dot, boxShadow: `0 0 20px ${finished ? '#10B98150' : dot + '45'}` }}
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
              {finished ? 'Complete!' : elapsed > 0 ? `Finish (${fmt(elapsed)})` : 'Mark Complete'}
            </button>
          </div>
          </div>{/* end ring+controls row */}

          {/* Block instruction */}
          {blocks && currentBlock && !finished && !blockTransition && (
            <p className="text-xs text-slate-500 text-center mt-2.5 max-w-xs leading-relaxed px-2">
              {currentBlock.instruction}
            </p>
          )}

          {/* Block transition banner */}
          {blockTransition && (
            <div className="mt-3 w-full max-w-sm rounded-xl px-4 py-3 text-center" style={{ backgroundColor: `${blockColor}15`, border: `1px solid ${blockColor}35` }}>
              <p className="text-sm font-semibold" style={{ color: blockColor }}>Block complete ✓ — Next: {blockTransition.nextTitle}</p>
              <p className="text-xs text-slate-500 mt-1 leading-relaxed">{blockTransition.nextInstruction}</p>
            </div>
          )}

          {/* Segmented block bar */}
          {blocks && (
            <div className="flex w-full max-w-xs gap-1 mt-3">
              {blocks.map((block, i) => {
                const ac = ACTIVITY_COLORS[block.activity] ?? dot
                const isDone = completedBlocks.has(i)
                const isCurrent = i === blockIdx
                return (
                  <div key={i} className="flex-1 flex flex-col items-center gap-1">
                    <div
                      className="w-full h-1.5 rounded-full transition-all"
                      style={{ backgroundColor: isDone ? ac : isCurrent ? ac : ac + '30' }}
                    />
                    {isDone && <span style={{ fontSize: '8px', color: ac }}>✓</span>}
                  </div>
                )
              })}
            </div>
          )}
        </div>

        {/* Divider */}
        <div className="h-px bg-slate-800/80 shrink-0" />

        {/* Tab bar */}
        <div className="flex items-center px-3 pt-2.5 pb-0 gap-0.5 shrink-0 overflow-x-auto">
          {[
            { id: 'recall', label: 'Active Recall' },
            { id: 'flashcards', label: 'Flashcards' },
            { id: 'quiz', label: 'Quick Quiz' },
            { id: 'notes', label: 'Notes' },
            { id: 'ai', label: 'Ask AI' },
          ].map(({ id, label }) => (
            <button
              key={id}
              onClick={() => visitTab(id)}
              className="px-3.5 py-2 rounded-xl text-sm font-medium transition-all whitespace-nowrap"
              style={activeTab === id
                ? { backgroundColor: `${dot}20`, color: dot, boxShadow: `0 0 12px ${dot}20` }
                : { color: '#64748b' }
              }
            >
              {label}
              {tabsVisited.has(id) && activeTab !== id && (
                <span className="ml-1.5 inline-block w-1.5 h-1.5 rounded-full align-middle" style={{ backgroundColor: `${dot}60` }} />
              )}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className={`flex-1 ${activeTab === 'ai' ? 'flex flex-col overflow-hidden' : 'overflow-y-auto'}`}>
          {activeTab === 'ai' && (
            <AIChatView
              courseId={session.courseId}
              courseName={session.courseName}
              examDate={course?.examDate ?? null}
              targetGrade={course?.targetGrade ?? null}
              userId={userId}
              onShowPaywall={onShowPaywall}
            />
          )}
          <div className={activeTab === 'ai' ? 'hidden' : 'px-5 py-4'}>

            {/* ── Active Recall ── */}
            {activeTab === 'recall' && (
              <div className="space-y-3">
                <div>
                  <p className="text-slate-200 font-semibold text-sm mb-0.5">
                    Without looking at your notes, write down everything you know about{' '}
                    <span style={{ color: dot }}>{session.courseName}</span>{' '}
                    — {session.sessionType}.
                  </p>
                  <p className="text-slate-600 text-xs leading-relaxed">Spend at least 5 minutes on this. The act of retrieving information is what builds memory.</p>
                </div>

                <div className="relative">
                  <textarea
                    value={recallText}
                    onChange={e => { setRecallText(e.target.value); setRecallSaved(false) }}
                    placeholder="Start writing everything you know…"
                    className="w-full min-h-48 rounded-2xl px-4 py-3 text-slate-100 placeholder-slate-700 focus:outline-none text-sm resize-none leading-relaxed"
                    style={{
                      backgroundColor: '#111827',
                      border: `1px solid #1e293b`,
                      boxShadow: 'inset 0 2px 8px rgba(0,0,0,0.3)',
                    }}
                  />
                  <div className="absolute bottom-3 right-3 flex items-center gap-3">
                    {recallWritingTimer > 0 && (
                      <span className="text-slate-700 text-xs font-mono">{fmt(recallWritingTimer)}</span>
                    )}
                    <span className="text-slate-700 text-xs">{wordCount(recallText)} words</span>
                  </div>
                </div>

                {!showRecallCards ? (
                  <button
                    onClick={handleCheckYourself}
                    className="w-full py-3.5 rounded-xl font-semibold text-white text-sm transition-all"
                    style={{
                      backgroundColor: dot,
                      boxShadow: `0 0 18px ${dot}30`,
                      animation: checkPulse ? 'checkPulse 2s ease-in-out infinite' : 'none',
                    }}
                  >
                    Check Yourself
                  </button>
                ) : (
                  <div className="space-y-3">
                    {flashcards.length > 0 ? (
                      <>
                        <div className="flex items-center justify-between">
                          <p className="text-xs font-medium uppercase tracking-widest" style={{ color: dot }}>Quick check</p>
                          <span className="text-xs text-slate-500">Card {rcIdx + 1} of {flashcards.length}</span>
                        </div>
                        <div className="relative cursor-pointer select-none" style={{ perspective: '1200px', height: '150px' }} onClick={() => setRcFlipped(f => !f)}>
                          <div className="absolute inset-0 rounded-2xl" style={{ transformStyle: 'preserve-3d', WebkitTransformStyle: 'preserve-3d', transition: 'transform 0.55s cubic-bezier(0.4,0,0.2,1)', transform: rcFlipped ? 'rotateY(180deg)' : 'rotateY(0)' }}>
                            <div className="absolute inset-0 rounded-2xl flex items-center justify-center p-5 text-center" style={{ backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden', backgroundColor: '#111827', border: '1px solid #1e293b' }}>
                              <p className="text-slate-100 font-medium text-sm leading-relaxed">{flashcards[rcIdx]?.front}</p>
                            </div>
                            <div className="absolute inset-0 rounded-2xl flex items-center justify-center p-5 text-center" style={{ backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden', backgroundColor: `${dot}15`, border: `1px solid ${dot}35`, transform: 'rotateY(180deg)', WebkitTransform: 'rotateY(180deg)' }}>
                              <p className="text-slate-200 text-sm leading-relaxed">{flashcards[rcIdx]?.back}</p>
                            </div>
                          </div>
                        </div>
                        <p className="text-center text-xs text-slate-700">Tap to flip</p>
                        <div className="flex gap-2">
                          <button onClick={() => { setRcIdx(i => Math.max(0, i - 1)); setRcFlipped(false) }} disabled={rcIdx === 0} className="flex-1 py-2 rounded-xl text-sm text-slate-400 bg-slate-800 border border-slate-700 disabled:opacity-30 hover:bg-slate-700 transition-colors">← Prev</button>
                          <button onClick={() => { setRcIdx(i => Math.min(flashcards.length - 1, i + 1)); setRcFlipped(false) }} disabled={rcIdx === flashcards.length - 1} className="flex-1 py-2 rounded-xl text-sm text-slate-400 bg-slate-800 border border-slate-700 disabled:opacity-30 hover:bg-slate-700 transition-colors">Next →</button>
                        </div>
                      </>
                    ) : (
                      <div className="bg-slate-800/40 border border-slate-700/40 rounded-2xl p-5 text-center">
                        <p className="text-slate-400 text-sm">Upload course notes in <span className="font-medium" style={{ color: dot }}>Study Tools</span> to unlock personalized recall checks.</p>
                      </div>
                    )}
                  </div>
                )}

                {recallSaved && (
                  <p className="text-xs text-emerald-500 flex items-center gap-1">
                    <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" /></svg>
                    Recall entry saved
                  </p>
                )}
              </div>
            )}

            {/* ── Flashcards ── */}
            {activeTab === 'flashcards' && (
              <>
                {flashcards.length > 0 ? (
                  <div>
                    <div className="flex items-center justify-between mb-4">
                      <p className="text-xs uppercase tracking-widest font-medium" style={{ color: dot }}>
                        Card {fcIdx + 1} of {flashcards.length}
                        {fcKnown.size > 0 && <span className="text-slate-600"> · {fcKnown.size} mastered</span>}
                      </p>
                      <div className="flex gap-1">
                        {flashcards.map((_, i) => (
                          <div key={i} className="w-1.5 h-1.5 rounded-full transition-colors" style={{ backgroundColor: fcKnown.has(i) ? '#10B981' : i === fcIdx ? dot : '#1e293b' }} />
                        ))}
                      </div>
                    </div>

                    {/* Swipe indicators + card */}
                    <div className="relative flex items-center gap-2 mb-3">
                      <button
                        onClick={() => { setFcIdx(i => Math.max(0, i - 1)); setFcFlipped(false) }}
                        disabled={fcIdx === 0}
                        className="shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-slate-600 hover:text-slate-300 disabled:opacity-20 transition-colors bg-slate-800/60"
                      >
                        ‹
                      </button>

                      <div className="flex-1 relative cursor-pointer select-none" style={{ perspective: '1200px', height: '210px' }} onClick={() => setFcFlipped(f => !f)}>
                        <div
                          className="absolute inset-0 rounded-2xl"
                          style={{
                            transformStyle: 'preserve-3d',
                            WebkitTransformStyle: 'preserve-3d',
                            transition: 'transform 0.6s cubic-bezier(0.4,0,0.2,1)',
                            transform: fcFlipped ? 'rotateY(180deg)' : 'rotateY(0)',
                            filter: fcFlipped ? `drop-shadow(0 0 20px ${dot}30)` : 'none',
                          }}
                        >
                          <div
                            className="absolute inset-0 rounded-2xl flex flex-col items-center justify-center p-6 text-center"
                            style={{ backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden', backgroundColor: '#111827', border: '1px solid #1e293b', boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.04)' }}
                          >
                            {flashcards[fcIdx]?.topic && (
                              <span className="text-xs mb-3 px-2 py-0.5 rounded-full border font-medium uppercase tracking-wide" style={{ color: dot, borderColor: `${dot}40`, backgroundColor: `${dot}10` }}>{flashcards[fcIdx].topic}</span>
                            )}
                            <p className="text-slate-100 font-semibold leading-relaxed text-base">{flashcards[fcIdx]?.front}</p>
                            <p className="text-slate-700 text-xs mt-4">Tap card to reveal answer</p>
                          </div>
                          <div
                            className="absolute inset-0 rounded-2xl flex items-center justify-center p-6 text-center"
                            style={{ backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden', backgroundColor: `${dot}10`, border: `1px solid ${dot}30`, transform: 'rotateY(180deg)', WebkitTransform: 'rotateY(180deg)' }}
                          >
                            <p className="text-slate-200 leading-relaxed text-base">{flashcards[fcIdx]?.back}</p>
                          </div>
                        </div>
                      </div>

                      <button
                        onClick={() => { setFcIdx(i => Math.min(flashcards.length - 1, i + 1)); setFcFlipped(false) }}
                        disabled={fcIdx === flashcards.length - 1}
                        className="shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-slate-600 hover:text-slate-300 disabled:opacity-20 transition-colors bg-slate-800/60"
                      >
                        ›
                      </button>
                    </div>

                    <p className="text-center text-xs text-slate-700 mb-3">← → or tap arrows to navigate · tap card to flip</p>

                    <div className="flex gap-2">
                      <button
                        onClick={() => { setFcKnown(prev => { const n = new Set(prev); n.has(fcIdx) ? n.delete(fcIdx) : n.add(fcIdx); return n }) }}
                        className="flex-1 py-2.5 rounded-xl text-sm font-medium transition-colors border"
                        style={fcKnown.has(fcIdx)
                          ? { backgroundColor: '#064e3b', borderColor: '#059669', color: '#34d399' }
                          : { borderColor: '#1e293b', color: '#64748b' }
                        }
                      >
                        {fcKnown.has(fcIdx) ? '✓ Mastered' : 'Mark as Mastered'}
                      </button>
                      <button
                        onClick={() => setFcKnown(prev => { const n = new Set(prev); n.delete(fcIdx); return n })}
                        className="flex-1 py-2.5 rounded-xl text-sm font-medium text-slate-600 border border-slate-800 hover:border-slate-700 hover:text-slate-400 transition-colors"
                      >
                        Still Learning
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="flex flex-col items-center justify-center py-12 text-center">
                    <div className="w-20 h-20 rounded-3xl flex items-center justify-center mb-5" style={{ backgroundColor: `${dot}12`, border: `1px dashed ${dot}30` }}>
                      <svg className="w-10 h-10" style={{ color: dot, opacity: 0.7 }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                      </svg>
                    </div>
                    <p className="text-white font-bold text-lg mb-2">Generate flashcards for this session</p>
                    <p className="text-slate-500 text-sm mb-6 max-w-xs">
                      {notesConcepts || notesMain || notesSummary
                        ? 'Flashcards will be generated from your session notes and course materials.'
                        : 'Add notes in the Notes tab for more relevant flashcards, or generate from course materials.'}
                    </p>
                    {fcGenerateError && (
                      <div className="bg-red-950/40 border border-red-800/40 rounded-xl px-4 py-3 text-red-300 text-sm mb-4 w-full max-w-xs">{fcGenerateError}</div>
                    )}
                    {fcGenerating ? (
                      <div className="flex flex-col items-center gap-3">
                        <div className="w-8 h-8 border-4 rounded-full animate-spin" style={{ borderColor: `${dot}30`, borderTopColor: dot }} />
                        <p className="text-slate-400 text-sm">Generating flashcards…</p>
                      </div>
                    ) : (
                      <button
                        onClick={handleGenerateFlashcards}
                        className="px-5 py-2.5 rounded-xl text-sm font-semibold transition-all"
                        style={{ backgroundColor: `${dot}20`, color: dot, border: `1px solid ${dot}40` }}
                      >
                        Generate Flashcards
                      </button>
                    )}
                  </div>
                )}
              </>
            )}

            {/* ── Quick Quiz ── */}
            {activeTab === 'quiz' && (
              <>
                {quizLoading ? (
                  <div className="flex flex-col items-center gap-3 py-14">
                    <div className="w-8 h-8 border-4 rounded-full animate-spin" style={{ borderColor: `${dot}30`, borderTopColor: dot }} />
                    <p className="text-slate-400 text-sm">Generating your quiz…</p>
                  </div>
                ) : quizError ? (
                  <div className="space-y-3">
                    <div className="bg-red-950/40 border border-red-800/40 rounded-xl px-4 py-3 text-red-300 text-sm">{quizError}</div>
                    <button onClick={handleGenerateQuiz} className="w-full py-3 rounded-xl text-sm font-medium bg-slate-800 border border-slate-700 text-slate-300 hover:bg-slate-700 transition-colors">Try Again</button>
                  </div>
                ) : !quizQuestions ? (
                  <div className="flex flex-col items-center text-center py-6">
                    <div className="w-20 h-20 rounded-3xl flex items-center justify-center mb-5" style={{ backgroundColor: `${dot}15`, border: `1px solid ${dot}25` }}>
                      <svg className="w-10 h-10" style={{ color: dot }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                      </svg>
                    </div>
                    <p className="text-white font-bold text-xl mb-2">Test yourself right now</p>
                    <p className="text-slate-500 text-sm mb-5 max-w-xs">5 AI-generated questions based on {session.courseName}{studyTools ? ' — pulled from your uploaded notes' : ''}.</p>
                    <div className="flex gap-2 mb-7">
                      {['Multiple Choice', '5 Questions', 'AI-Generated'].map(tag => (
                        <span key={tag} className="text-xs px-2.5 py-1 rounded-full font-medium" style={{ backgroundColor: `${dot}12`, color: dot, border: `1px solid ${dot}30` }}>{tag}</span>
                      ))}
                    </div>
                    <button
                      onClick={handleGenerateQuiz}
                      className="w-full py-4 rounded-xl font-bold text-white text-base transition-all"
                      style={{ backgroundColor: dot, boxShadow: `0 0 24px ${dot}40` }}
                    >
                      Generate 5-Question Quiz
                    </button>
                  </div>
                ) : quizDone ? (
                  <div>
                    <div className="text-center mb-6">
                      <p className="text-5xl font-bold text-white mb-1 font-mono">
                        {quizAnswers.filter(a => a.correct).length}<span className="text-slate-700 text-3xl">/{quizQuestions.length}</span>
                      </p>
                      <p className="font-semibold" style={{ color: dot }}>
                        {quizAnswers.filter(a => a.correct).length === quizQuestions.length ? 'Perfect score!'
                          : quizAnswers.filter(a => a.correct).length >= quizQuestions.length * 0.8 ? 'Great work!'
                          : 'Keep reviewing!'}
                      </p>
                    </div>
                    <div className="space-y-2.5 mb-5">
                      {quizAnswers.map((a, i) => (
                        <div key={i} className="rounded-xl p-3.5 border" style={a.correct ? { backgroundColor: '#022c22', borderColor: '#065f46' } : { backgroundColor: '#1c0606', borderColor: '#7f1d1d' }}>
                          <div className="flex items-start gap-2 mb-1">
                            <span className="text-xs font-bold shrink-0 mt-0.5" style={{ color: a.correct ? '#34d399' : '#f87171' }}>{a.correct ? '✓' : '✗'}</span>
                            <p className="text-slate-200 text-sm leading-relaxed">{a.question.question}</p>
                          </div>
                          {!a.correct && <p className="text-xs text-slate-500 ml-4 mt-1">Correct: {a.question.answer}</p>}
                          {a.question.explanation && <p className="text-xs text-slate-700 ml-4 mt-0.5 italic">{a.question.explanation}</p>}
                        </div>
                      ))}
                    </div>
                    <button onClick={resetQuiz} className="w-full py-3 rounded-xl text-sm font-medium text-slate-300 bg-slate-800 border border-slate-700 hover:bg-slate-700 transition-colors">New Quiz</button>
                  </div>
                ) : (
                  <div style={{ animation: quizAnswerFlash === 'correct' ? 'flashGreen 0.5s ease' : quizAnswerFlash === 'wrong' ? 'shakeRed 0.5s ease' : 'none' }}>
                    <div className="flex items-center justify-between mb-4">
                      <p className="text-xs uppercase tracking-widest font-medium" style={{ color: dot }}>Question {quizIdx + 1} of {quizQuestions.length}</p>
                      <div className="flex gap-1.5">
                        {quizQuestions.map((_, i) => (
                          <div key={i} className="w-2 h-2 rounded-full transition-colors" style={{ backgroundColor: i < quizIdx ? (quizAnswers[i]?.correct ? '#10B981' : '#ef4444') : i === quizIdx ? dot : '#1e293b' }} />
                        ))}
                      </div>
                    </div>
                    <p className="text-white font-semibold mb-5 leading-relaxed text-base">{quizQuestions[quizIdx]?.question}</p>
                    <div className="space-y-2.5 mb-4">
                      {quizQuestions[quizIdx]?.options.map((opt, i) => {
                        const isSelected = quizSelected === opt
                        const isCorrect = quizConfirmed && opt === quizQuestions[quizIdx].answer
                        const isWrong = quizConfirmed && isSelected && !isCorrect
                        return (
                          <button
                            key={i}
                            onClick={() => !quizConfirmed && setQuizSelected(opt)}
                            className="w-full text-left px-4 py-3.5 rounded-xl border text-sm transition-all font-medium"
                            style={
                              isCorrect ? { backgroundColor: '#064e3b', borderColor: '#059669', color: '#34d399' }
                              : isWrong ? { backgroundColor: '#450a0a', borderColor: '#b91c1c', color: '#f87171' }
                              : isSelected ? { borderColor: dot, backgroundColor: `${dot}18`, color: 'white' }
                              : { borderColor: '#1e293b', color: '#94a3b8', backgroundColor: 'transparent' }
                            }
                          >
                            {opt}
                          </button>
                        )
                      })}
                    </div>
                    {quizConfirmed && quizQuestions[quizIdx]?.explanation && (
                      <div className="rounded-xl px-4 py-3 mb-4" style={{ backgroundColor: `${dot}08`, border: `1px solid ${dot}20` }}>
                        <p className="text-slate-400 text-xs leading-relaxed italic">{quizQuestions[quizIdx].explanation}</p>
                      </div>
                    )}
                    <button
                      onClick={quizConfirmed ? handleNextQuestion : handleConfirmAnswer}
                      disabled={!quizConfirmed && quizSelected === null}
                      className="w-full py-3.5 rounded-xl text-sm font-bold text-white disabled:opacity-30 transition-all"
                      style={{ backgroundColor: quizConfirmed || quizSelected ? dot : '#1e293b', boxShadow: (quizConfirmed || quizSelected) ? `0 0 16px ${dot}35` : 'none' }}
                    >
                      {quizConfirmed ? (quizIdx + 1 >= quizQuestions.length ? 'See Results' : 'Next Question →') : 'Check Answer'}
                    </button>
                  </div>
                )}
              </>
            )}

            {/* ── Notes ── */}
            {activeTab === 'notes' && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-xs uppercase tracking-widest font-bold" style={{ color: dot }}>{session.courseName}</p>
                    <p className="text-xs text-slate-600">{todayStr} · {session.sessionType}</p>
                  </div>
                  {notesAutoSaved && (
                    <span className="text-xs text-emerald-500 flex items-center gap-1 transition-opacity">
                      <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" /></svg>
                      Auto-saved
                    </span>
                  )}
                </div>

                {/* Cornell layout */}
                <div className="flex gap-0 rounded-2xl overflow-hidden border border-slate-800">
                  {/* Key Concepts column */}
                  <div className="w-[32%] border-r border-slate-800">
                    <div className="px-3 py-2 border-b border-slate-800" style={{ backgroundColor: `${dot}08` }}>
                      <p className="text-xs font-bold uppercase tracking-wider" style={{ color: dot }}>Key Concepts</p>
                      <p className="text-xs text-slate-700">{notesConcepts.length} chars</p>
                    </div>
                    <textarea
                      ref={conceptsRef}
                      value={notesConcepts}
                      onChange={e => { setNotesConcepts(e.target.value); autoGrow(e) }}
                      placeholder={'• concept\n• term = ...\n• key idea'}
                      className="w-full bg-transparent px-3 py-2.5 text-slate-300 placeholder-slate-800 focus:outline-none text-xs resize-none leading-relaxed"
                      style={{ minHeight: '200px' }}
                    />
                  </div>
                  {/* Notes column */}
                  <div className="flex-1">
                    <div className="px-3 py-2 border-b border-slate-800" style={{ backgroundColor: `${dot}05` }}>
                      <p className="text-xs font-bold uppercase tracking-wider" style={{ color: dot }}>Notes</p>
                      <p className="text-xs text-slate-700">{notesMain.length} chars</p>
                    </div>
                    <textarea
                      ref={mainRef}
                      value={notesMain}
                      onChange={e => { setNotesMain(e.target.value); autoGrow(e) }}
                      placeholder="Write your notes here…"
                      className="w-full bg-transparent px-3 py-2.5 text-slate-200 placeholder-slate-800 focus:outline-none text-sm resize-none leading-relaxed"
                      style={{ minHeight: '200px' }}
                    />
                  </div>
                </div>

                {/* Summary */}
                <div className="rounded-2xl overflow-hidden border border-slate-800">
                  <div className="px-3 py-2 border-b border-slate-800" style={{ backgroundColor: `${dot}06` }}>
                    <div className="flex items-center justify-between">
                      <p className="text-xs font-bold uppercase tracking-wider" style={{ color: dot }}>Summary</p>
                      <p className="text-xs text-slate-700">{notesSummary.length} chars</p>
                    </div>
                  </div>
                  <textarea
                    ref={summaryRef}
                    value={notesSummary}
                    onChange={e => { setNotesSummary(e.target.value); autoGrow(e) }}
                    placeholder="In 2-3 sentences, summarize what you studied today…"
                    className="w-full bg-transparent px-3 py-2.5 text-slate-200 placeholder-slate-800 focus:outline-none text-sm resize-none leading-relaxed"
                    style={{ minHeight: '80px' }}
                  />
                </div>

                {/* Action buttons */}
                <div className="flex gap-2.5">
                  <button
                    onClick={handleSaveNotes}
                    className="flex-1 py-3 rounded-xl text-sm font-semibold transition-all flex items-center justify-center gap-2 border"
                    style={notesSaved
                      ? { backgroundColor: '#064e3b', borderColor: '#059669', color: '#34d399' }
                      : { borderColor: '#1e293b', color: '#94a3b8', backgroundColor: 'transparent' }
                    }
                  >
                    {notesSaved
                      ? <><svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" /></svg>Saved!</>
                      : <><svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" /></svg>Save Notes</>
                    }
                  </button>
                  <button
                    onClick={handleDownloadPDF}
                    disabled={pdfDownloading || !hasNotes}
                    className="flex-1 py-3 rounded-xl text-sm font-semibold transition-all flex items-center justify-center gap-2 text-white disabled:opacity-40"
                    style={{ backgroundColor: dot, boxShadow: hasNotes ? `0 0 16px ${dot}30` : 'none' }}
                  >
                    <svg className="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    {pdfDownloading ? 'Generating…' : 'Download PDF'}
                  </button>
                </div>
              </div>
            )}

          </div>
        </div>
      </div>

      <style>{`
        @keyframes breathe {
          0%, 100% { transform: scale(1); }
          50% { transform: scale(1.3); }
        }
        @keyframes ringPulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.78; }
        }
        @keyframes checkPulse {
          0%, 100% { box-shadow: 0 0 18px ${dot}30; }
          50% { box-shadow: 0 0 36px ${dot}70, 0 0 60px ${dot}30; }
        }
        @keyframes flashGreen {
          0%, 100% { background-color: transparent; }
          30% { background-color: rgba(16,185,129,0.08); }
        }
        @keyframes shakeRed {
          0%, 100% { transform: translateX(0); }
          20% { transform: translateX(-6px); }
          40% { transform: translateX(6px); }
          60% { transform: translateX(-4px); }
          80% { transform: translateX(4px); }
        }
      `}</style>
    </div>
  )
}
