import { useState, useEffect, useRef, useCallback } from 'react'
import {
  getCachedStudyTools,
  getCachedNotes,
  saveNotes as dbSaveNotes,
  appendSessionRecall,
} from '../lib/db'
import { getAccessToken } from '../lib/supabase'
import { canUseAI, incrementAIQuery } from '../lib/subscription'
import { useCelebration } from '../utils/useCelebration'
import { extractText } from '../utils/extractText'
import AIChatView from './AIChatView'

function fmt(seconds) {
  const m = Math.floor(seconds / 60).toString().padStart(2, '0')
  const s = (seconds % 60).toString().padStart(2, '0')
  return `${m}:${s}`
}

function wordCount(text) {
  return text.trim() ? text.trim().split(/\s+/).length : 0
}

function loadStudyTools(courseId) {
  const data = getCachedStudyTools()
  return data?.courseIdx === courseId ? data : null
}

function saveNotes(courseId, dateStr, notes) {
  dbSaveNotes(courseId, dateStr, notes)
}

function loadNotes(courseId, dateStr) {
  return getCachedNotes(courseId, dateStr)
}

function appendRecall(courseId, courseName, sessionType, text) {
  appendSessionRecall({ courseId, courseName, sessionType, text, timestamp: Date.now() })
}

async function loadJsPDF() {
  if (window.jspdf?.jsPDF) return window.jspdf.jsPDF
  return new Promise((resolve, reject) => {
    const s = document.createElement('script')
    s.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js'
    s.onload = () => resolve(window.jspdf.jsPDF)
    s.onerror = () => reject(new Error('Failed to load jsPDF'))
    document.head.appendChild(s)
  })
}

async function generatePDF({ courseName, dateStr, sessionType, recallText, concepts, main, summary }) {
  const JsPDF = await loadJsPDF()
  const doc = new JsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = 210
  const margin = 18
  const contentW = pageW - margin * 2
  let y = 20

  const addText = (text, x, size, color, bold) => {
    doc.setFontSize(size)
    doc.setTextColor(...color)
    if (bold) doc.setFont('helvetica', 'bold')
    else doc.setFont('helvetica', 'normal')
    doc.text(text, x, y)
  }

  const addWrapped = (text, x, size, color, maxW) => {
    doc.setFontSize(size)
    doc.setTextColor(...color)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(text, maxW)
    doc.text(lines, x, y)
    y += lines.length * (size * 0.4 + 1)
  }

  const section = (title) => {
    y += 4
    doc.setFillColor(245, 247, 252)
    doc.roundedRect(margin, y - 5, contentW, 9, 2, 2, 'F')
    doc.setFontSize(10)
    doc.setTextColor(80, 80, 120)
    doc.setFont('helvetica', 'bold')
    doc.text(title, margin + 4, y + 1)
    y += 8
  }

  // ── Header ──
  doc.setFillColor(99, 102, 241)
  doc.rect(0, 0, pageW, 14, 'F')
  doc.setFontSize(12)
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.text('StudyEdge AI Session Notes', margin, 9)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`${dateStr}`, pageW - margin, 9, { align: 'right' })
  y = 24

  addText(`${courseName}`, margin, 18, [20, 20, 40], true)
  y += 9
  addText(`${sessionType} Session`, margin, 11, [100, 100, 130], false)
  y += 8
  doc.setDrawColor(220, 220, 235)
  doc.line(margin, y, pageW - margin, y)
  y += 8

  // ── Sections ──
  if (recallText?.trim()) {
    section('Active Recall')
    addWrapped(recallText.trim(), margin, 10, [40, 40, 60], contentW)
    y += 4
  }

  if (concepts?.trim()) {
    section('Key Concepts')
    addWrapped(concepts.trim(), margin, 10, [40, 40, 60], contentW)
    y += 4
  }

  if (main?.trim()) {
    section('Session Notes')
    addWrapped(main.trim(), margin, 10, [40, 40, 60], contentW)
    y += 4
  }

  if (summary?.trim()) {
    section('Summary')
    addWrapped(summary.trim(), margin, 10, [40, 40, 60], contentW)
    y += 4
  }

  // ── Footer ──
  const pageH = 297
  doc.setFontSize(8)
  doc.setTextColor(160, 160, 180)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by StudyEdge AI • studyedge.app', pageW / 2, pageH - 8, { align: 'center' })

  const filename = `StudyEdge AI_${courseName.replace(/\s+/g, '_')}_${dateStr}.pdf`
  doc.save(filename)
}

const ENCOURAGE = [
  'Great session! Every minute you put in compounds into exam-day confidence.',
  'Solid work. Consistent sessions like this are what separate top performers.',
  "You showed up and did the work. That's what matters most.",
  'Another session in the books. Your future self thanks you.',
]

const ACTIVITY_COLORS = {
  'review':            '#3B82F6',
  'active-recall':     '#A855F7',
  'flashcards':        '#EC4899',
  'practice-problems': '#F97316',
  'summary':           '#14B8A6',
  'break':             '#22C55E',
}

export default function FocusMode({ session, blueprint, onComplete, onExit, nextSession, onStartNext, onGoToTools, course, onShowPaywall, userId }) {
  const totalSec = session.duration * 60
  const isLongSession = session.duration > 45
  const todayStr = new Date().toISOString().split('T')[0]

  // ── Blueprint blocks ──
  const blocks = blueprint?.blocks ?? null
  const [blockIdx, setBlockIdx] = useState(0)
  const [blockRemaining, setBlockRemaining] = useState(() => blocks ? blocks[0].duration * 60 : totalSec)
  const [completedBlocks, setCompletedBlocks] = useState(new Set())
  const [blockTransition, setBlockTransition] = useState(null) // { title, nextTitle, nextInstruction }
  const blockAdvanceRef = useRef(null)

  const currentBlock = blocks ? blocks[blockIdx] : null
  const nextBlock = blocks ? blocks[blockIdx + 1] : null
  const blockColor = currentBlock ? (ACTIVITY_COLORS[currentBlock.activity] ?? session.color.dot) : session.color.dot
  const blockPct = currentBlock ? (1 - blockRemaining / (currentBlock.duration * 60)) : 0

  // ── Timer ──
  const [remaining, setRemaining] = useState(totalSec)
  const [running, setRunning] = useState(true)
  const [finished, setFinished] = useState(false)
  const intervalRef = useRef(null)

  // ── Tabs ──
  const [activeTab, setActiveTab] = useState('recall')
  const [tabsVisited, setTabsVisited] = useState(new Set(['recall']))

  // ── Completion ──
  const [showComplete, setShowComplete] = useState(false)
  const [encourageMsg] = useState(() => blueprint?.successNote ?? ENCOURAGE[Math.floor(Math.random() * ENCOURAGE.length)])
  const celebrate = useCelebration()
  const celebratedRef = useRef(false)
  useEffect(() => {
    if (showComplete && !celebratedRef.current) {
      celebratedRef.current = true
      celebrate('big')
    }
  }, [showComplete])
  const [pdfDownloading, setPdfDownloading] = useState(false)

  // ── Pomodoro ──
  const BREAK_INTERVAL = 25 * 60
  const BREAK_DURATION = 5 * 60
  const [breakBanner, setBreakBanner] = useState(false)
  const [breakOverlay, setBreakOverlay] = useState(false)
  const [breakRemaining, setBreakRemaining] = useState(BREAK_DURATION)
  const lastBreakCount = useRef(0)

  // ── Study tools ──
  const [studyTools] = useState(() => loadStudyTools(session.courseId))
  const [inSessionFlashcards, setInSessionFlashcards] = useState(null)
  const [fcGenerating, setFcGenerating] = useState(false)
  const [fcGenerateError, setFcGenerateError] = useState('')
  const flashcards = inSessionFlashcards ?? []

  // ── Active Recall ──
  const [recallText, setRecallText] = useState('')
  const [recallSaved, setRecallSaved] = useState(false)
  const [showRecallCards, setShowRecallCards] = useState(false)
  const [rcIdx, setRcIdx] = useState(0)
  const [rcFlipped, setRcFlipped] = useState(false)
  const [recallWritingTimer, setRecallWritingTimer] = useState(0)
  const recallTimerRef = useRef(null)
  const recallStartedRef = useRef(false)
  const lastTypedRef = useRef(0)
  const [checkPulse, setCheckPulse] = useState(false)

  // ── Flashcards ──
  const [fcIdx, setFcIdx] = useState(0)
  const [fcFlipped, setFcFlipped] = useState(false)
  const [fcKnown, setFcKnown] = useState(new Set())
  const [fcAnswerState, setFcAnswerState] = useState(null) // 'correct' | 'wrong' | null

  // ── Quick Quiz ──
  const [quizQuestions, setQuizQuestions] = useState(null)
  const [quizLoading, setQuizLoading] = useState(false)
  const [quizError, setQuizError] = useState('')
  const [quizIdx, setQuizIdx] = useState(0)
  const [quizAnswers, setQuizAnswers] = useState([])
  const [quizSelected, setQuizSelected] = useState(null)
  const [quizConfirmed, setQuizConfirmed] = useState(false)
  const [quizDone, setQuizDone] = useState(false)
  const [quizAnswerFlash, setQuizAnswerFlash] = useState(null) // 'correct' | 'wrong'

  // ── Quiz/Flashcard custom source (topic + uploaded files/images) ──
  const [quizTopic, setQuizTopic] = useState(() => {
    const parts = [session.focusArea, ...(session.keyTopics ?? [])].filter(Boolean)
    return parts.length ? parts.slice(0, 3).join(', ') : ''
  })
  const [quizSourceText, setQuizSourceText] = useState('')
  const [quizSourceImages, setQuizSourceImages] = useState([]) // { name, dataUrl, media_type, data }
  const [quizSourceFiles, setQuizSourceFiles] = useState([])   // [{ name }]
  const [quizSourceLoading, setQuizSourceLoading] = useState(false)

  const [fcTopic, setFcTopic] = useState(() => {
    const parts = [session.focusArea, ...(session.keyTopics ?? [])].filter(Boolean)
    return parts.length ? parts.slice(0, 3).join(', ') : ''
  })
  const [fcSourceText, setFcSourceText] = useState('')
  const [fcSourceImages, setFcSourceImages] = useState([])
  const [fcSourceFiles, setFcSourceFiles] = useState([])
  const [fcSourceLoading, setFcSourceLoading] = useState(false)

  // ── Notes ──
  const [notesConcepts, setNotesConcepts] = useState('')
  const [notesMain, setNotesMain] = useState('')
  const [notesSummary, setNotesSummary] = useState('')
  const [notesSaved, setNotesSaved] = useState(false)
  const [notesAutoSaved, setNotesAutoSaved] = useState(false)
  const notesSaveRef = useRef(null)
  const conceptsRef = useRef(null)
  const mainRef = useRef(null)
  const summaryRef = useRef(null)

  // ── Load saved notes ──
  useEffect(() => {
    const saved = loadNotes(session.courseId, todayStr)
    if (saved) {
      setNotesConcepts(saved.concepts ?? '')
      setNotesMain(saved.main ?? '')
      setNotesSummary(saved.summary ?? '')
    }
  }, [])

  // ── Auto-resize textareas after load ──
  useEffect(() => {
    [conceptsRef, mainRef, summaryRef].forEach(r => {
      if (r.current) { r.current.style.height = 'auto'; r.current.style.height = r.current.scrollHeight + 'px' }
    })
  }, [notesConcepts, notesMain, notesSummary])

  // ── Timer countdown ──
  useEffect(() => {
    if (!running || finished) return
    intervalRef.current = setInterval(() => {
      // Overall timer
      setRemaining(r => {
        if (r <= 1) { clearInterval(intervalRef.current); setRunning(false); setFinished(true); return 0 }
        return r - 1
      })
      // Block timer
      if (blocks) {
        setBlockRemaining(r => {
          if (r <= 1) return 0
          return r - 1
        })
      }
    }, 1000)
    return () => clearInterval(intervalRef.current)
  }, [running, finished, blocks])

  // ── Block advance when block timer hits 0 ──
  useEffect(() => {
    if (!blocks || blockRemaining > 0 || finished) return
    const current = blocks[blockIdx]
    const next = blocks[blockIdx + 1]
    // Mark block complete
    setCompletedBlocks(prev => new Set([...prev, blockIdx]))
    if (!next) return // last block; overall timer will handle finish

    // Show transition banner
    setBlockTransition({ title: current.title, nextTitle: next.title, nextInstruction: next.instruction })
    setRunning(false)

    blockAdvanceRef.current = setTimeout(() => {
      setBlockIdx(i => i + 1)
      setBlockRemaining(next.duration * 60)
      setBlockTransition(null)
      setRunning(true)
    }, 4000)

    return () => clearTimeout(blockAdvanceRef.current)
  }, [blockRemaining])

  // ── Auto-show complete ──
  useEffect(() => {
    if (finished) { const t = setTimeout(() => setShowComplete(true), 1200); return () => clearTimeout(t) }
  }, [finished])

  // ── Pomodoro banner ──
  useEffect(() => {
    if (!isLongSession || !running || finished) return
    const elapsed = totalSec - remaining
    const count = Math.floor(elapsed / BREAK_INTERVAL)
    if (count > lastBreakCount.current) { lastBreakCount.current = count; setBreakBanner(true) }
  }, [remaining])

  // ── Break countdown ──
  useEffect(() => {
    if (!breakOverlay) return
    setBreakRemaining(BREAK_DURATION)
    const t = setInterval(() => {
      setBreakRemaining(r => {
        if (r <= 1) { clearInterval(t); setBreakOverlay(false); setBreakBanner(false); return BREAK_DURATION }
        return r - 1
      })
    }, 1000)
    return () => clearInterval(t)
  }, [breakOverlay])

  // ── Recall writing timer ──
  useEffect(() => {
    if (recallText && !recallStartedRef.current) {
      recallStartedRef.current = true
      recallTimerRef.current = setInterval(() => setRecallWritingTimer(t => t + 1), 1000)
    }
    if (recallText) lastTypedRef.current = Date.now()
    return () => {}
  }, [recallText])

  useEffect(() => () => clearInterval(recallTimerRef.current), [])

  // ── Check Yourself pulse after 3 min inactivity ──
  useEffect(() => {
    if (!recallText || showRecallCards) return
    const check = setInterval(() => {
      if (Date.now() - lastTypedRef.current > 180000) setCheckPulse(true)
      else setCheckPulse(false)
    }, 10000)
    return () => clearInterval(check)
  }, [recallText, showRecallCards])

  // ── Notes auto-save ──
  useEffect(() => {
    clearTimeout(notesSaveRef.current)
    if (!notesConcepts && !notesMain && !notesSummary) return
    notesSaveRef.current = setTimeout(() => {
      saveNotes(session.courseId, todayStr, { concepts: notesConcepts, main: notesMain, summary: notesSummary })
      setNotesAutoSaved(true)
      setTimeout(() => setNotesAutoSaved(false), 2000)
    }, 2000)
    return () => clearTimeout(notesSaveRef.current)
  }, [notesConcepts, notesMain, notesSummary])

  // ── Escape key ──
  useEffect(() => {
    const handler = e => { if (e.key === 'Escape' && !showComplete) onExit() }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [onExit, showComplete])

  // ── Derived ──
  const elapsed = totalSec - remaining
  const pct = blocks ? blockPct : (totalSec > 0 ? elapsed / totalSec : 0)
  const strokeColor = finished ? '#10B981' : (blocks ? blockColor : session.color.dot)
  const R = 78
  const CIRC = 2 * Math.PI * R
  const dot = session.color.dot
  const hasNotes = !!(notesConcepts.trim() || notesMain.trim() || notesSummary.trim() || recallText.trim())

  // ── Handlers ──
  const visitTab = tab => { setActiveTab(tab); setTabsVisited(prev => new Set([...prev, tab])) }
  const handleMarkComplete = () => { if (running) setRunning(false); setShowComplete(true) }

  const handleSkipBlock = () => {
    if (!blocks || !nextBlock) return
    clearTimeout(blockAdvanceRef.current)
    setCompletedBlocks(prev => new Set([...prev, blockIdx]))
    setBlockTransition(null)
    setBlockIdx(i => i + 1)
    setBlockRemaining(nextBlock.duration * 60)
    setRunning(true)
  }
  const handleBackToDashboard = () => onComplete(session.id, elapsed)
  const handleStartNext = () => { if (nextSession && onStartNext) onStartNext(session.id, elapsed, nextSession); else onComplete(session.id, elapsed) }

  const handleCheckYourself = () => {
    if (recallText.trim()) appendRecall(session.courseId, session.courseName, session.sessionType, recallText)
    setRecallSaved(true); setShowRecallCards(true); setRcIdx(0); setRcFlipped(false)
  }

  const handleGenerateQuiz = async () => {
    if (!canUseAI()) { onShowPaywall?.('ai'); return }
    setQuizLoading(true); setQuizError(''); setQuizQuestions(null)
    setQuizAnswers([]); setQuizIdx(0); setQuizSelected(null); setQuizConfirmed(false); setQuizDone(false)
    try {
      const token = await getAccessToken()
      const res = await fetch('/api/generate-study-tools', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({
          mode: 'quick-quiz',
          courseName: session.courseName,
          sessionType: session.sessionType,
          topic: quizTopic.trim(),
          text: [
            quizSourceText && `Uploaded materials:\n${quizSourceText.slice(0, 6000)}`,
            notesConcepts && `Key concepts:\n${notesConcepts}`,
            notesMain && `Notes:\n${notesMain}`,
            notesSummary && `Summary:\n${notesSummary}`,
            studyTools?.text?.slice(0, 3000),
          ].filter(Boolean).join('\n\n') || '',
          images: quizSourceImages.map(img => ({ media_type: img.media_type, data: img.data })),
        }),
      })
      if (!res.ok) {
        let errMsg = 'Quiz generation failed'
        try { const d = await res.json(); errMsg = d.error ?? errMsg } catch {}
        throw new Error(errMsg)
      }
      const data = await res.json()
      setQuizQuestions(data.questions)
      incrementAIQuery()
    } catch (e) { setQuizError(e.message) }
    finally { setQuizLoading(false) }
  }

  const handleConfirmAnswer = () => {
    if (quizSelected === null) return
    const q = quizQuestions[quizIdx]
    const correct = quizSelected === q.answer
    setQuizAnswers(prev => [...prev, { selected: quizSelected, correct, question: q }])
    setQuizConfirmed(true)
    setQuizAnswerFlash(correct ? 'correct' : 'wrong')
    setTimeout(() => setQuizAnswerFlash(null), 600)
  }

  const handleNextQuestion = () => {
    if (quizIdx + 1 >= quizQuestions.length) setQuizDone(true)
    else { setQuizIdx(i => i + 1); setQuizSelected(null); setQuizConfirmed(false) }
  }

  const resetQuiz = () => { setQuizQuestions(null); setQuizDone(false); setQuizAnswers([]); setQuizIdx(0); setQuizSelected(null); setQuizConfirmed(false) }

  const handleGenerateFlashcards = async () => {
    if (!canUseAI()) { onShowPaywall?.('ai'); return }
    const sessionNotes = [
      notesConcepts && `Key concepts:\n${notesConcepts}`,
      notesMain && `Notes:\n${notesMain}`,
      notesSummary && `Summary:\n${notesSummary}`,
    ].filter(Boolean).join('\n\n')
    const text = [
      fcSourceText && `Uploaded materials:\n${fcSourceText.slice(0, 6000)}`,
      sessionNotes,
      studyTools?.text?.slice(0, 4000),
    ].filter(Boolean).join('\n\n')
    const topic = fcTopic.trim()
    const hasImages = fcSourceImages.length > 0

    if (!topic && !hasImages && text.length < 50) {
      setFcGenerateError('Tell it what to study, upload a file, or add some notes first.')
      return
    }
    setFcGenerating(true); setFcGenerateError('')
    try {
      const token = await getAccessToken()
      const res = await fetch('/api/generate-study-tools', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({
          text,
          topic,
          images: fcSourceImages.map(img => ({ media_type: img.media_type, data: img.data })),
          creative: true,
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error ?? 'Failed to generate flashcards')
      setInSessionFlashcards(data.flashcards ?? [])
      incrementAIQuery()
      setFcIdx(0); setFcFlipped(false); setFcKnown(new Set())
    } catch (e) { setFcGenerateError(e.message) }
    finally { setFcGenerating(false) }
  }

  // ── File/image upload for quiz & flashcard generators ─────────────────────────
  const resizeImageToBase64 = (file) => new Promise((resolve, reject) => {
    const img = new Image()
    const reader = new FileReader()
    reader.onload = e => { img.src = e.target.result }
    reader.onerror = reject
    img.onload = () => {
      const MAX_W = 1400
      const scale = Math.min(1, MAX_W / img.width)
      const canvas = document.createElement('canvas')
      canvas.width = Math.round(img.width * scale)
      canvas.height = Math.round(img.height * scale)
      const ctx = canvas.getContext('2d')
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height)
      const dataUrl = canvas.toDataURL('image/jpeg', 0.75)
      const base64 = dataUrl.split(',')[1]
      resolve({ data: base64, media_type: 'image/jpeg' })
    }
    img.onerror = reject
    reader.readAsDataURL(file)
  })

  const handleUploadSource = async (mode, fileList) => {
    const setLoading = mode === 'quiz' ? setQuizSourceLoading : setFcSourceLoading
    const setText = mode === 'quiz' ? setQuizSourceText : setFcSourceText
    const setImages = mode === 'quiz' ? setQuizSourceImages : setFcSourceImages
    const setFiles = mode === 'quiz' ? setQuizSourceFiles : setFcSourceFiles
    const setError = mode === 'quiz' ? setQuizError : setFcGenerateError

    setLoading(true); setError('')
    try {
      for (const file of fileList) {
        const ext = file.name.split('.').pop().toLowerCase()
        if (['pdf', 'docx', 'pptx'].includes(ext)) {
          const text = await extractText(file)
          setText(prev => (prev ? prev + '\n\n' : '') + text)
          setFiles(prev => [...prev, { name: file.name }])
        } else if (['png', 'jpg', 'jpeg', 'gif', 'webp'].includes(ext)) {
          const img = await resizeImageToBase64(file)
          setImages(prev => [...prev, { name: file.name, ...img }])
          setFiles(prev => [...prev, { name: file.name }])
        } else {
          throw new Error(`Unsupported file: ${file.name}. Upload PDF, DOCX, PPTX, or an image.`)
        }
      }
    } catch (e) {
      setError(e.message ?? 'Failed to read file')
    } finally {
      setLoading(false)
    }
  }

  const clearQuizSource = () => {
    setQuizSourceText(''); setQuizSourceImages([]); setQuizSourceFiles([])
  }
  const clearFcSource = () => {
    setFcSourceText(''); setFcSourceImages([]); setFcSourceFiles([])
  }

  const handleSaveNotes = () => {
    saveNotes(session.courseId, todayStr, { concepts: notesConcepts, main: notesMain, summary: notesSummary })
    setNotesSaved(true); setTimeout(() => setNotesSaved(false), 2000)
  }

  const handleDownloadPDF = async () => {
    setPdfDownloading(true)
    try {
      await generatePDF({
        courseName: session.courseName, dateStr: todayStr, sessionType: session.sessionType,
        recallText, concepts: notesConcepts, main: notesMain, summary: notesSummary,
      })
    } catch (e) { console.error('PDF error:', e) }
    finally { setPdfDownloading(false) }
  }

  const autoGrow = e => { e.target.style.height = 'auto'; e.target.style.height = e.target.scrollHeight + 'px' }

  // Keyboard shortcuts
  useEffect(() => {
    const handler = e => {
      if (e.target.tagName === 'TEXTAREA' || e.target.tagName === 'INPUT') return
      if (e.key === ' ' || e.code === 'Space') { e.preventDefault(); setRunning(r => !r) }
      if (e.key === 'Enter') { e.preventDefault(); handleMarkComplete() }
      if (e.key === 'Escape') { e.preventDefault(); setActiveTab(null) }
      if (e.key === '1') visitTab('recall')
      if (e.key === '2') visitTab('flashcards')
      if (e.key === '3') visitTab('quiz')
      if (e.key === '4') visitTab('notes')
      if (e.key === '5') visitTab('ai')
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const SESSION_TABS = [
    { id: 'recall',     label: 'Active Recall', num: 1 },
    { id: 'flashcards', label: 'Flashcards',    num: 2 },
    { id: 'quiz',       label: 'Quick Quiz',    num: 3 },
    { id: 'notes',      label: 'Notes',         num: 4 },
    { id: 'ai',         label: 'Ask AI',        num: 5 },
  ]

  // ─── RENDER ─────────────────────────────────────────────────────────────────
  return (
    <div className="fixed inset-0 z-[100] flex flex-col overflow-hidden" style={{ backgroundColor: '#F7F6F3' }}>
      {/* Top accent line */}
      <div className="h-0.5 w-full shrink-0" style={{ backgroundColor: dot }} />

      {/* ── Pomodoro break banner ── */}
      {breakBanner && !breakOverlay && (
        <div className="relative z-10 flex items-center gap-3 px-4 py-2.5 shrink-0" style={{ backgroundColor: `${dot}18`, borderBottom: `1px solid ${dot}28` }}>
          <div className="w-2 h-2 rounded-full shrink-0 animate-pulse" style={{ backgroundColor: dot }} />
          <span className="text-xs" style={{ color: '#4B4B4B' }}>5-minute break recommended. You've been studying for 25 minutes</span>
          <div className="ml-auto flex items-center gap-2 shrink-0">
            <button onClick={() => setBreakOverlay(true)} className="text-xs px-3 py-1 rounded-lg font-medium text-white" style={{ backgroundColor: dot }}>Take Break</button>
            <button onClick={() => setBreakBanner(false)} className="text-xs transition-colors" style={{ color: '#9B9B9B' }}>Dismiss</button>
          </div>
        </div>
      )}

      {/* ── Break overlay ── */}
      {breakOverlay && (
        <div className="absolute inset-0 z-[110] flex flex-col items-center justify-center" style={{ backgroundColor: '#F7F6F3' }}>
          <div className="text-center">
            <div className="relative flex items-center justify-center mb-10">
              <div className="w-36 h-36 rounded-full" style={{ backgroundColor: dot, opacity: 0.08, animation: 'breathe 4s ease-in-out infinite' }} />
              <div className="absolute w-24 h-24 rounded-full" style={{ backgroundColor: dot, opacity: 0.15, animation: 'breathe 4s ease-in-out infinite 0.8s' }} />
              <div className="absolute w-12 h-12 rounded-full" style={{ backgroundColor: dot }} />
            </div>
            <h2 className="text-3xl font-bold mb-2" style={{ color: '#1A1A1A' }}>Take a breath</h2>
            <p className="text-sm mb-3" style={{ color: '#6B6B6B' }}>Inhale 4s &nbsp;·&nbsp; Hold 4s &nbsp;·&nbsp; Exhale 4s</p>
            <p className="text-5xl font-mono font-bold mb-8" style={{ color: dot }}>{fmt(breakRemaining)}</p>
            <button onClick={() => { setBreakOverlay(false); setBreakBanner(false) }} className="text-sm transition-colors" style={{ color: '#9B9B9B' }}>Skip break, keep studying</button>
          </div>
        </div>
      )}

      {/* ── Session complete screen ── */}
      {showComplete && (
        <div className="absolute inset-0 z-[105] flex flex-col items-center justify-center px-6 overflow-y-auto py-10" style={{ backgroundColor: '#F7F6F3' }}>
          <div className="w-full max-w-sm">
            {/* Check mark */}
            <div className="flex items-center justify-center mb-8">
              <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke={dot} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M5 13l4 4L19 7" />
              </svg>
            </div>

            <h2 className="text-2xl font-bold text-center mb-2" style={{ color: '#1A1A1A' }}>Session Complete</h2>
            <p className="text-center text-sm mb-8 leading-relaxed" style={{ color: '#9B9B9B' }}>{encourageMsg}</p>

            {/* Stats inline row */}
            <div className="flex items-center justify-center gap-8 mb-8" style={{ borderTop: '1px solid rgba(0,0,0,0.07)', borderBottom: '1px solid rgba(0,0,0,0.07)', padding: '16px 0' }}>
              <div className="text-center">
                <p className="text-xl font-bold font-mono" style={{ color: '#1A1A1A' }}>{fmt(Math.max(elapsed, 1))}</p>
                <p className="text-xs mt-0.5" style={{ color: '#9B9B9B' }}>Time studied</p>
              </div>
              <div style={{ width: 1, height: 32, backgroundColor: 'rgba(0,0,0,0.07)' }} />
              <div className="text-center">
                <p className="text-xl font-bold font-mono" style={{ color: '#1A1A1A' }}>{tabsVisited.size}</p>
                <p className="text-xs mt-0.5" style={{ color: '#9B9B9B' }}>Activities used</p>
              </div>
            </div>

            {/* Activities used — simple list, no card */}
            <div className="mb-8">
              {[
                { id: 'recall', label: 'Active Recall' },
                { id: 'flashcards', label: 'Flashcards' },
                { id: 'quiz', label: 'Quick Quiz' },
                { id: 'notes', label: 'Notes' },
              ].map(({ id, label }) => (
                <div key={id} className="flex items-center gap-2.5 py-1.5">
                  <div className="w-4 h-4 rounded-full flex items-center justify-center shrink-0" style={{ backgroundColor: tabsVisited.has(id) ? dot : 'rgba(0,0,0,0.07)' }}>
                    {tabsVisited.has(id) && (
                      <svg width="8" height="8" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                        <path d="M5 13l4 4L19 7" />
                      </svg>
                    )}
                  </div>
                  <span className="text-sm" style={{ color: tabsVisited.has(id) ? '#1A1A1A' : '#C0C0C0' }}>{label}</span>
                </div>
              ))}
            </div>

            <div className="flex flex-col gap-2.5">
              {hasNotes && (
                <button
                  onClick={handleDownloadPDF}
                  disabled={pdfDownloading}
                  className="w-full py-3 rounded-xl text-sm font-medium transition-colors flex items-center justify-center gap-2"
                  style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#6B6B6B' }}
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  {pdfDownloading ? 'Generating PDF…' : 'Download Session Notes'}
                </button>
              )}
              {nextSession && (
                <button onClick={handleStartNext} className="w-full py-3.5 rounded-2xl font-bold text-white text-sm" style={{ backgroundColor: dot }}>
                  Start Next: {nextSession.courseName}
                </button>
              )}
              <button onClick={handleBackToDashboard} className="w-full py-3 rounded-xl text-sm font-medium transition-colors" style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#6B6B6B' }}>
                Back to Dashboard
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Main session layout ── */}
      <div className="relative flex flex-col h-full overflow-hidden">

        {/* ── Top bar ── */}
        <div className="relative flex items-center px-5 py-3 shrink-0" style={{ backgroundColor: '#FFFFFF', borderBottom: '1px solid rgba(0,0,0,0.07)' }}>
          {/* Left: course info */}
          <div className="flex items-center gap-2 flex-1 min-w-0">
            <div className="rounded-full shrink-0" style={{ width: 8, height: 8, backgroundColor: dot }} />
            <span className="font-semibold text-sm truncate" style={{ color: '#1A1A1A' }}>{session.courseName}</span>
            <span className="shrink-0" style={{ color: 'rgba(0,0,0,0.18)', fontSize: 12 }}>·</span>
            <span className="text-xs shrink-0" style={{ color: '#9B9B9B' }}>{session.sessionType}</span>
          </div>
          {/* Center: label */}
          <div className="absolute left-1/2 -translate-x-1/2 pointer-events-none">
            <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#C0C0C0' }}>Focus Session</span>
          </div>
          {/* Right: elapsed + exit */}
          <div className="flex items-center gap-4 shrink-0">
            <span style={{ fontSize: 12, color: '#9B9B9B', fontFamily: 'ui-monospace, monospace' }}>
              {fmt(elapsed)} <span style={{ color: '#C0C0C0' }}>/ {String(session.duration).padStart(2,'0')}:00</span>
            </span>
            <button onClick={onExit} className="text-xs transition-colors" style={{ color: '#9B9B9B' }}>Exit</button>
          </div>
        </div>

        {/* ── Block info + segmented progress bar ── */}
        {blocks && (
          <div className="shrink-0 px-6 pt-3 pb-2" style={{ backgroundColor: '#FFFFFF', borderBottom: '1px solid rgba(0,0,0,0.07)' }}>
            {currentBlock && !finished && (
              <div className="flex items-center gap-2 mb-2">
                <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', color: blockColor }}>
                  Block {String(blockIdx + 1).padStart(2, '0')}/{String(blocks.length).padStart(2, '0')}
                </span>
                <span style={{ color: 'rgba(0,0,0,0.15)', fontSize: 10 }}>·</span>
                <span style={{ fontSize: 13, color: '#1A1A1A', fontWeight: 500 }}>{currentBlock.title}</span>
                {currentBlock.activity && (
                  <>
                    <span style={{ color: 'rgba(0,0,0,0.15)', fontSize: 10 }}>·</span>
                    <span style={{ fontSize: 11, color: '#9B9B9B', fontStyle: 'italic' }}>{currentBlock.activity}</span>
                  </>
                )}
              </div>
            )}
            <div style={{ display: 'flex', gap: 3 }}>
              {blocks.map((b, i) => {
                const ac = ACTIVITY_COLORS[b.activity] ?? dot
                const isDone = completedBlocks.has(i)
                const isCurrent = i === blockIdx
                return (
                  <div key={i} style={{ flex: 1, height: 3, borderRadius: 2, backgroundColor: isDone ? ac : isCurrent ? ac : ac + '28', transition: 'background-color 0.4s' }} />
                )
              })}
            </div>
          </div>
        )}

        {/* ── Timer + controls (hero section) ── */}
        <div className="flex-1 flex flex-col items-center justify-center px-6 min-h-0" style={{ minHeight: 160, overflow: 'hidden' }}>
          {finished ? (
            <div className="flex flex-col items-center gap-3">
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke={dot} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M5 13l4 4L19 7" />
              </svg>
              <p style={{ fontSize: 14, color: '#9B9B9B' }}>Session complete</p>
            </div>
          ) : (
            <>
              {/* Huge timer */}
              <div
                style={{
                  fontSize: 'clamp(4.5rem, 14vw, 8.5rem)',
                  fontWeight: 800,
                  fontFamily: '"SF Mono", "Fira Code", ui-monospace, monospace',
                  letterSpacing: '-0.03em',
                  lineHeight: 1,
                  color: running ? '#1A1A1A' : '#C0C0C0',
                  transition: 'color 0.3s',
                  userSelect: 'none',
                  tabularNums: true,
                }}
              >
                {fmt(blocks ? blockRemaining : remaining)}
              </div>

              {/* Sub-label */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 10, fontSize: 12, color: '#9B9B9B' }}>
                <span>{blocks ? 'remaining this block' : 'remaining'}</span>
                <span style={{ opacity: 0.35 }}>·</span>
                <span>{session.duration} min total</span>
              </div>

              {/* Block instruction */}
              {blocks && currentBlock && !blockTransition && (
                <p style={{ fontSize: 13, color: '#6B6B6B', marginTop: 18, textAlign: 'center', maxWidth: 420, lineHeight: 1.65 }}>
                  {currentBlock.instruction}
                </p>
              )}

              {/* Block transition */}
              {blockTransition && (
                <div style={{ marginTop: 16, padding: '10px 18px', borderRadius: 10, backgroundColor: `${blockColor}10`, border: `1px solid ${blockColor}28`, textAlign: 'center', maxWidth: 380 }}>
                  <p style={{ fontSize: 13, fontWeight: 600, color: blockColor }}>Block complete ✓ &nbsp;·&nbsp; Next: {blockTransition.nextTitle}</p>
                  <p style={{ fontSize: 12, color: '#6B6B6B', marginTop: 4 }}>{blockTransition.nextInstruction}</p>
                </div>
              )}

              {/* ── Control buttons ── */}
              <div style={{ display: 'flex', gap: 10, marginTop: 28, flexWrap: 'wrap', justifyContent: 'center' }}>
                {/* Pause / Resume */}
                <button
                  onClick={() => setRunning(r => !r)}
                  style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '10px 16px', borderRadius: 10, backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#6B6B6B', fontSize: 13, fontWeight: 500, cursor: 'pointer', lineHeight: 1 }}
                >
                  {running ? (
                    <svg width="13" height="13" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zM7 8a1 1 0 012 0v4a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v4a1 1 0 102 0V8a1 1 0 00-1-1z" clipRule="evenodd" /></svg>
                  ) : (
                    <svg width="13" height="13" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9.555 7.168A1 1 0 008 8v4a1 1 0 001.555.832l3-2a1 1 0 000-1.664l-3-2z" clipRule="evenodd" /></svg>
                  )}
                  <span>{running ? 'Pause' : 'Resume'}</span>
                  <span style={{ fontSize: 10, color: '#C0C0C0' }}>[Space]</span>
                </button>

                {/* Skip block */}
                {blocks && nextBlock && (
                  <button
                    onClick={handleSkipBlock}
                    style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '10px 16px', borderRadius: 10, backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#9B9B9B', fontSize: 13, fontWeight: 500, cursor: 'pointer', lineHeight: 1 }}
                  >
                    <span>Skip block</span>
                    <svg width="11" height="11" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M9 5l7 7-7 7" /></svg>
                  </button>
                )}

                {/* Finish / Mark complete */}
                <button
                  onClick={handleMarkComplete}
                  style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '10px 16px', borderRadius: 10, backgroundColor: '#1A1A1A', color: '#FFFFFF', fontSize: 13, fontWeight: 600, cursor: 'pointer', lineHeight: 1 }}
                >
                  <svg width="13" height="13" fill="none" stroke="currentColor" strokeWidth={2.5} strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24"><path d="M5 13l4 4L19 7" /></svg>
                  <span>{elapsed > 0 ? `Finish (${fmt(elapsed)})` : 'Finish block'}</span>
                  <span style={{ fontSize: 10, color: 'rgba(255,255,255,0.4)' }}>[↵]</span>
                </button>
              </div>

              {/* Keyboard hint */}
              <p style={{ fontSize: 11, color: '#C0C0C0', marginTop: 16 }}>
                [Space] pause &nbsp;·&nbsp; [↵] finish &nbsp;·&nbsp; [1–5] tools &nbsp;·&nbsp; [Esc] close panel
              </p>
            </>
          )}
        </div>

        {/* ── Tab panel (slides up from bottom) ── */}
        {activeTab && (
          <div
            className={activeTab === 'ai' ? 'flex flex-col overflow-hidden' : 'overflow-y-auto'}
            style={{ height: '40vh', borderTop: '1px solid rgba(0,0,0,0.07)', flexShrink: 0 }}
          >
            {/* AIChatView stays mounted */}
            <div className={activeTab === 'ai' ? 'flex-1 flex flex-col overflow-hidden h-full' : 'hidden'}>
              <AIChatView
                courseId={session.courseId}
                courseName={session.courseName}
                examDate={course?.examDate ?? null}
                targetGrade={course?.targetGrade ?? null}
                userId={userId}
                onShowPaywall={onShowPaywall}
              />
            </div>
            <div className={activeTab === 'ai' ? 'hidden' : 'px-5 py-4'}>

            {/* ── Active Recall ── */}
            {activeTab === 'recall' && (
              <div className="space-y-3">
                {/* Header row */}
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <p className="font-semibold text-sm leading-snug" style={{ color: '#1A1A1A' }}>
                      Without looking at your notes, write down everything you know about{' '}
                      <span style={{ color: dot }}>{session.courseName}</span>.
                    </p>
                    <p className="text-xs mt-1 leading-relaxed" style={{ color: '#9B9B9B' }}>The act of retrieving information is what builds memory. Aim for five minutes of free recall.</p>
                  </div>
                  <div className="shrink-0 text-right" style={{ fontSize: 12, color: '#C0C0C0', fontFamily: 'ui-monospace, monospace', whiteSpace: 'nowrap' }}>
                    {wordCount(recallText)} words
                    {recallWritingTimer > 0 && <span> · {fmt(recallWritingTimer)} elapsed</span>}
                  </div>
                </div>

                <textarea
                  value={recallText}
                  onChange={e => { setRecallText(e.target.value); setRecallSaved(false) }}
                  placeholder={`Start writing everything you remember about ${session.courseName}…`}
                  className="w-full rounded-xl px-4 py-3 focus:outline-none text-sm resize-none leading-relaxed"
                  style={{
                    minHeight: 120,
                    backgroundColor: '#FFFFFF',
                    border: '1px solid rgba(0,0,0,0.10)',
                    color: '#1A1A1A',
                  }}
                />

                {!showRecallCards ? (
                  <div className="flex items-center justify-between">
                    <button
                      onClick={() => { /* save for later — keep recallText, close panel */ setActiveTab(null) }}
                      className="text-sm transition-colors"
                      style={{ color: '#9B9B9B' }}
                    >
                      Save and continue later
                    </button>
                    <button
                      onClick={handleCheckYourself}
                      className="px-5 py-2 rounded-full font-semibold text-sm transition-all"
                      style={{
                        backgroundColor: dot,
                        color: '#FFFFFF',
                        animation: checkPulse ? 'checkPulse 2s ease-in-out infinite' : 'none',
                      }}
                    >
                      Check yourself
                    </button>
                  </div>
                ) : (
                  <div className="space-y-3">
                    {flashcards.length > 0 ? (
                      <>
                        <div className="flex items-center justify-between">
                          <p className="text-xs font-medium uppercase tracking-widest" style={{ color: dot }}>Quick check</p>
                          <span className="text-xs text-slate-500">Card {rcIdx + 1} of {flashcards.length}</span>
                        </div>
                        <div className="relative cursor-pointer select-none" style={{ perspective: '1200px', height: '150px' }} onClick={() => setRcFlipped(f => !f)}>
                          <div className="absolute inset-0 rounded-2xl" style={{ transformStyle: 'preserve-3d', WebkitTransformStyle: 'preserve-3d', transition: 'transform 0.55s cubic-bezier(0.4,0,0.2,1)', transform: rcFlipped ? 'rotateY(180deg)' : 'rotateY(0)' }}>
                            <div className="absolute inset-0 rounded-2xl flex items-center justify-center p-5 text-center" style={{ backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden', backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)' }}>
                              <p className="font-medium text-sm leading-relaxed" style={{ color: '#1A1A1A' }}>{flashcards[rcIdx]?.front}</p>
                            </div>
                            <div className="absolute inset-0 rounded-2xl flex items-center justify-center p-5 text-center" style={{ backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden', backgroundColor: `${dot}10`, border: `1px solid ${dot}30`, transform: 'rotateY(180deg)', WebkitTransform: 'rotateY(180deg)' }}>
                              <p className="text-sm leading-relaxed" style={{ color: '#1A1A1A' }}>{flashcards[rcIdx]?.back}</p>
                            </div>
                          </div>
                        </div>
                        <p className="text-center text-xs" style={{ color: '#C0C0C0' }}>Tap to flip</p>
                        <div className="flex gap-2">
                          <button onClick={() => { setRcIdx(i => Math.max(0, i - 1)); setRcFlipped(false) }} disabled={rcIdx === 0} className="flex-1 py-2 rounded-xl text-sm transition-colors disabled:opacity-30" style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#6B6B6B' }}>← Prev</button>
                          <button onClick={() => { setRcIdx(i => Math.min(flashcards.length - 1, i + 1)); setRcFlipped(false) }} disabled={rcIdx === flashcards.length - 1} className="flex-1 py-2 rounded-xl text-sm transition-colors disabled:opacity-30" style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#6B6B6B' }}>Next →</button>
                        </div>
                      </>
                    ) : (
                      <div className="rounded-2xl p-5 text-center" style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.07)' }}>
                        <p className="text-sm" style={{ color: '#9B9B9B' }}>Upload course notes in <span className="font-medium" style={{ color: dot }}>Study Tools</span> to unlock personalized recall checks.</p>
                      </div>
                    )}
                  </div>
                )}

                {recallSaved && (
                  <p className="text-xs text-emerald-500 flex items-center gap-1">
                    <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" /></svg>
                    Recall entry saved
                  </p>
                )}
              </div>
            )}

            {/* ── Flashcards ── */}
            {activeTab === 'flashcards' && (
              <>
                {flashcards.length > 0 ? (
                  <div>
                    <div className="flex items-center justify-between mb-4">
                      <p className="text-xs uppercase tracking-widest font-medium" style={{ color: dot }}>
                        Card {fcIdx + 1} of {flashcards.length}
                        {fcKnown.size > 0 && <span className="text-slate-600"> · {fcKnown.size} mastered</span>}
                      </p>
                      <div className="flex gap-1">
                        {flashcards.map((_, i) => (
                          <div key={i} className="w-1.5 h-1.5 rounded-full transition-colors" style={{ backgroundColor: fcKnown.has(i) ? '#10B981' : i === fcIdx ? dot : 'rgba(0,0,0,0.12)' }} />
                        ))}
                      </div>
                    </div>

                    {/* Swipe indicators + card */}
                    <div className="relative flex items-center gap-2 mb-3">
                      <button
                        onClick={() => { setFcIdx(i => Math.max(0, i - 1)); setFcFlipped(false) }}
                        disabled={fcIdx === 0}
                        className="shrink-0 w-8 h-8 rounded-full flex items-center justify-center disabled:opacity-20 transition-colors"
                        style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#9B9B9B' }}
                      >
                        ‹
                      </button>

                      <div
                        className="flex-1 relative cursor-pointer select-none rounded-2xl transition-all duration-200"
                        style={{
                          minHeight: '210px',
                          backgroundColor: fcFlipped ? `${dot}08` : '#FFFFFF',
                          border: fcFlipped ? `1px solid ${dot}40` : '1px solid rgba(0,0,0,0.10)',
                        }}
                        onClick={() => setFcFlipped(f => !f)}
                      >
                        {!fcFlipped ? (
                          <div className="absolute inset-0 rounded-2xl flex flex-col items-center justify-center p-6 text-center">
                            {flashcards[fcIdx]?.topic && (
                              <span className="text-xs mb-3 px-2 py-0.5 rounded-full border font-medium uppercase tracking-wide" style={{ color: dot, borderColor: `${dot}40`, backgroundColor: `${dot}15` }}>{flashcards[fcIdx].topic}</span>
                            )}
                            <p className="font-semibold leading-relaxed text-base" style={{ color: '#1A1A1A' }}>{flashcards[fcIdx]?.front}</p>
                            <p className="text-xs mt-4" style={{ color: '#C0C0C0' }}>Tap card to reveal answer</p>
                          </div>
                        ) : (
                          <div className="absolute inset-0 rounded-2xl flex flex-col items-center justify-center p-6 text-center">
                            <span className="text-[10px] mb-3 px-2 py-0.5 rounded-full font-bold uppercase tracking-widest" style={{ color: dot, backgroundColor: `${dot}15`, border: `1px solid ${dot}40` }}>Answer</span>
                            <p className="font-semibold leading-relaxed text-base" style={{ color: dot }}>{flashcards[fcIdx]?.back}</p>
                            <p className="text-xs mt-4" style={{ color: '#C0C0C0' }}>Tap card to flip back</p>
                          </div>
                        )}
                      </div>

                      <button
                        onClick={() => { setFcIdx(i => Math.min(flashcards.length - 1, i + 1)); setFcFlipped(false) }}
                        disabled={fcIdx === flashcards.length - 1}
                        className="shrink-0 w-8 h-8 rounded-full flex items-center justify-center disabled:opacity-20 transition-colors"
                        style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#9B9B9B' }}
                      >
                        ›
                      </button>
                    </div>

                    <p className="text-center text-xs mb-3" style={{ color: '#C0C0C0' }}>← → or tap arrows to navigate · tap card to flip</p>

                    <div className="flex gap-2">
                      <button
                        onClick={() => { setFcKnown(prev => { const n = new Set(prev); n.has(fcIdx) ? n.delete(fcIdx) : n.add(fcIdx); return n }) }}
                        className="flex-1 py-2.5 rounded-xl text-sm font-medium transition-colors border"
                        style={fcKnown.has(fcIdx)
                          ? { backgroundColor: '#F0FDF4', borderColor: '#86EFAC', color: '#16A34A' }
                          : { backgroundColor: '#FFFFFF', borderColor: 'rgba(0,0,0,0.10)', color: '#6B6B6B' }
                        }
                      >
                        {fcKnown.has(fcIdx) ? '✓ Mastered' : 'Mark as Mastered'}
                      </button>
                      <button
                        onClick={() => setFcKnown(prev => { const n = new Set(prev); n.delete(fcIdx); return n })}
                        className="flex-1 py-2.5 rounded-xl text-sm font-medium transition-colors"
                        style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#6B6B6B' }}
                      >
                        Still Learning
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-3">
                    <div>
                      <p className="font-semibold text-sm" style={{ color: '#1A1A1A' }}>Build flashcards on demand</p>
                      <p className="text-xs mt-1 leading-relaxed" style={{ color: '#9B9B9B' }}>Describe what to drill on, attach a PDF or slides, and StudyEdge will generate cards on exactly what you asked for. Nothing more.</p>
                    </div>

                    <div className="flex gap-2 items-start">
                      <input
                        value={fcTopic}
                        onChange={e => setFcTopic(e.target.value)}
                        onKeyDown={e => e.key === 'Enter' && !fcGenerating && handleGenerateFlashcards()}
                        placeholder={`e.g. Memory systems: encoding, storage, retrieval, sensory and working memory`}
                        className="flex-1 rounded-xl px-3 py-2.5 text-sm focus:outline-none"
                        style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#1A1A1A' }}
                      />
                      <div className="flex items-center gap-2 shrink-0">
                        <label className="cursor-pointer flex items-center gap-1.5 px-3 py-2.5 rounded-xl text-sm transition-colors" style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#9B9B9B' }} title="Attach PDF or slides">
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" /></svg>
                          {fcSourceFiles.length > 0 && <span style={{ fontSize: 11, color: dot }}>{fcSourceFiles.length}</span>}
                          <input type="file" className="hidden" multiple accept=".pdf,.docx,.pptx,image/*" onChange={async e => { if (e.target.files?.length) await handleUploadSource('fc', Array.from(e.target.files)); e.target.value = '' }} />
                        </label>
                        <button
                          onClick={handleGenerateFlashcards}
                          disabled={fcGenerating}
                          className="px-4 py-2.5 rounded-xl text-sm font-semibold transition-all disabled:opacity-50"
                          style={{ backgroundColor: dot, color: '#FFFFFF' }}
                        >
                          {fcGenerating ? 'Generating…' : 'Generate'}
                        </button>
                      </div>
                    </div>

                    {fcSourceFiles.length > 0 && (
                      <div className="flex items-center gap-2 flex-wrap">
                        {fcSourceFiles.map((f, i) => (
                          <span key={i} className="text-xs px-2 py-1 rounded-lg" style={{ backgroundColor: `${dot}10`, color: dot }}>📎 {f.name}</span>
                        ))}
                        <button onClick={clearFcSource} className="text-xs" style={{ color: '#C0C0C0' }}>Clear</button>
                      </div>
                    )}

                    {fcGenerateError && (
                      <div className="rounded-xl px-4 py-3 text-sm" style={{ backgroundColor: '#FEF2F2', border: '1px solid #FCA5A5', color: '#DC2626' }}>{fcGenerateError}</div>
                    )}
                  </div>
                )}
              </>
            )}

            {/* ── Quick Quiz ── */}
            {activeTab === 'quiz' && (
              <>
                {quizLoading ? (
                  <div className="flex flex-col items-center gap-3 py-14">
                    <div className="w-8 h-8 border-4 rounded-full animate-spin" style={{ borderColor: `${dot}20`, borderTopColor: dot }} />
                    <p className="text-sm" style={{ color: '#9B9B9B' }}>Generating your quiz…</p>
                  </div>
                ) : quizError ? (
                  <div className="space-y-3">
                    <div className="rounded-xl px-4 py-3 text-sm" style={{ backgroundColor: '#FEF2F2', border: '1px solid #FCA5A5', color: '#DC2626' }}>{quizError}</div>
                    <button onClick={handleGenerateQuiz} className="w-full py-3 rounded-xl text-sm font-medium transition-colors" style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#6B6B6B' }}>Try Again</button>
                  </div>
                ) : !quizQuestions ? (
                  <div className="space-y-3">
                    <div>
                      <p className="font-semibold text-sm" style={{ color: '#1A1A1A' }}>Test yourself, your way</p>
                      <p className="text-xs mt-1 leading-relaxed" style={{ color: '#9B9B9B' }}>Describe exactly what to quiz you on, attach source material, or both. The quiz will only cover what you asked for.</p>
                    </div>

                    <div className="flex gap-2 items-start">
                      <input
                        value={quizTopic}
                        onChange={e => setQuizTopic(e.target.value)}
                        onKeyDown={e => e.key === 'Enter' && !quizLoading && handleGenerateQuiz()}
                        placeholder={`e.g. Three types of market structures from Chapter 6`}
                        className="flex-1 rounded-xl px-3 py-2.5 text-sm focus:outline-none"
                        style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#1A1A1A' }}
                      />
                      <div className="flex items-center gap-2 shrink-0">
                        <label className="cursor-pointer flex items-center gap-1.5 px-3 py-2.5 rounded-xl text-sm transition-colors" style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#9B9B9B' }} title="Attach PDF or slides">
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" /></svg>
                          {quizSourceFiles.length > 0 && <span style={{ fontSize: 11, color: dot }}>{quizSourceFiles.length}</span>}
                          <input type="file" className="hidden" multiple accept=".pdf,.docx,.pptx,image/*" onChange={async e => { if (e.target.files?.length) await handleUploadSource('quiz', Array.from(e.target.files)); e.target.value = '' }} />
                        </label>
                        <button
                          onClick={handleGenerateQuiz}
                          disabled={quizLoading}
                          className="px-4 py-2.5 rounded-xl text-sm font-semibold transition-all disabled:opacity-50"
                          style={{ backgroundColor: dot, color: '#FFFFFF' }}
                        >
                          {quizLoading ? 'Generating…' : 'Generate'}
                        </button>
                      </div>
                    </div>

                    {quizSourceFiles.length > 0 && (
                      <div className="flex items-center gap-2 flex-wrap">
                        {quizSourceFiles.map((f, i) => (
                          <span key={i} className="text-xs px-2 py-1 rounded-lg" style={{ backgroundColor: `${dot}10`, color: dot }}>📎 {f.name}</span>
                        ))}
                        <button onClick={clearQuizSource} className="text-xs" style={{ color: '#C0C0C0' }}>Clear</button>
                      </div>
                    )}
                  </div>
                ) : quizDone ? (
                  <div>
                    <div className="text-center mb-6">
                      <p className="text-5xl font-bold mb-1 font-mono" style={{ color: '#1A1A1A' }}>
                        {quizAnswers.filter(a => a.correct).length}<span className="text-3xl" style={{ color: '#C0C0C0' }}>/{quizQuestions.length}</span>
                      </p>
                      <p className="font-semibold" style={{ color: dot }}>
                        {quizAnswers.filter(a => a.correct).length === quizQuestions.length ? 'Perfect score!'
                          : quizAnswers.filter(a => a.correct).length >= quizQuestions.length * 0.8 ? 'Great work!'
                          : 'Keep reviewing!'}
                      </p>
                    </div>
                    <div className="space-y-2.5 mb-5">
                      {quizAnswers.map((a, i) => (
                        <div key={i} className="rounded-xl p-3.5 border" style={a.correct ? { backgroundColor: '#F0FDF4', borderColor: '#86EFAC' } : { backgroundColor: '#FEF2F2', borderColor: '#FCA5A5' }}>
                          <div className="flex items-start gap-2 mb-1">
                            <span className="text-xs font-bold shrink-0 mt-0.5" style={{ color: a.correct ? '#16A34A' : '#DC2626' }}>{a.correct ? '✓' : '✗'}</span>
                            <p className="text-sm leading-relaxed" style={{ color: '#1A1A1A' }}>{a.question.question}</p>
                          </div>
                          {!a.correct && <p className="text-xs ml-4 mt-1" style={{ color: '#6B6B6B' }}>Correct: {a.question.answer}</p>}
                          {a.question.explanation && <p className="text-xs ml-4 mt-0.5 italic" style={{ color: '#9B9B9B' }}>{a.question.explanation}</p>}
                        </div>
                      ))}
                    </div>
                    <button onClick={resetQuiz} className="w-full py-3 rounded-xl text-sm font-medium transition-colors" style={{ backgroundColor: '#FFFFFF', border: '1px solid rgba(0,0,0,0.10)', color: '#6B6B6B' }}>New Quiz</button>
                  </div>
                ) : (
                  <div style={{ animation: quizAnswerFlash === 'correct' ? 'flashGreen 0.5s ease' : quizAnswerFlash === 'wrong' ? 'shakeRed 0.5s ease' : 'none' }}>
                    <div className="flex items-center justify-between mb-4">
                      <p className="text-xs uppercase tracking-widest font-medium" style={{ color: dot }}>Question {quizIdx + 1} of {quizQuestions.length}</p>
                      <div className="flex gap-1.5">
                        {quizQuestions.map((_, i) => (
                          <div key={i} className="w-2 h-2 rounded-full transition-colors" style={{ backgroundColor: i < quizIdx ? (quizAnswers[i]?.correct ? '#10B981' : '#ef4444') : i === quizIdx ? dot : 'rgba(0,0,0,0.12)' }} />
                        ))}
                      </div>
                    </div>
                    <p className="font-semibold mb-5 leading-relaxed text-base" style={{ color: '#1A1A1A' }}>{quizQuestions[quizIdx]?.question}</p>
                    <div className="space-y-2.5 mb-4">
                      {quizQuestions[quizIdx]?.options.map((opt, i) => {
                        const isSelected = quizSelected === opt
                        const isCorrect = quizConfirmed && opt === quizQuestions[quizIdx].answer
                        const isWrong = quizConfirmed && isSelected && !isCorrect
                        return (
                          <button
                            key={i}
                            onClick={() => !quizConfirmed && setQuizSelected(opt)}
                            className="w-full text-left px-4 py-3.5 rounded-xl border text-sm transition-all font-medium"
                            style={
                              isCorrect ? { backgroundColor: '#F0FDF4', borderColor: '#86EFAC', color: '#16A34A' }
                              : isWrong ? { backgroundColor: '#FEF2F2', borderColor: '#FCA5A5', color: '#DC2626' }
                              : isSelected ? { borderColor: dot, backgroundColor: `${dot}12`, color: '#1A1A1A' }
                              : { borderColor: 'rgba(0,0,0,0.10)', color: '#6B6B6B', backgroundColor: '#FFFFFF' }
                            }
                          >
                            {opt}
                          </button>
                        )
                      })}
                    </div>
                    {quizConfirmed && quizQuestions[quizIdx]?.explanation && (
                      <div className="rounded-xl px-4 py-3 mb-4" style={{ backgroundColor: `${dot}08`, border: `1px solid ${dot}20` }}>
                        <p className="text-xs leading-relaxed italic" style={{ color: '#9B9B9B' }}>{quizQuestions[quizIdx].explanation}</p>
                      </div>
                    )}
                    <button
                      onClick={quizConfirmed ? handleNextQuestion : handleConfirmAnswer}
                      disabled={!quizConfirmed && quizSelected === null}
                      className="w-full py-3.5 rounded-xl text-sm font-bold text-white disabled:opacity-30 transition-all"
                      style={{ backgroundColor: quizConfirmed || quizSelected ? dot : 'rgba(0,0,0,0.08)' }}
                    >
                      {quizConfirmed ? (quizIdx + 1 >= quizQuestions.length ? 'See Results' : 'Next Question →') : 'Check Answer'}
                    </button>
                  </div>
                )}
              </>
            )}

            {/* ── Notes ── */}
            {activeTab === 'notes' && (
              <div className="space-y-3">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <p className="font-semibold text-sm" style={{ color: '#1A1A1A' }}>Today's notes</p>
                    <p className="text-xs mt-0.5 leading-relaxed" style={{ color: '#9B9B9B' }}>
                      Capture key concepts, definitions, and a short summary. Saved to{' '}
                      <strong style={{ color: '#6B6B6B', fontWeight: 600 }}>{session.courseName} · {session.sessionType}</strong> automatically.
                    </p>
                  </div>
                  <div className="flex items-center gap-3 shrink-0">
                    {notesAutoSaved && (
                      <span className="text-xs flex items-center gap-1" style={{ color: '#10B981' }}>
                        <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" /></svg>
                        Saved
                      </span>
                    )}
                    <button
                      onClick={handleDownloadPDF}
                      disabled={pdfDownloading || !hasNotes}
                      className="flex items-center gap-1.5 text-xs transition-colors disabled:opacity-40"
                      style={{ color: '#9B9B9B' }}
                    >
                      <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                      </svg>
                      {pdfDownloading ? 'Generating…' : 'Export PDF'}
                    </button>
                  </div>
                </div>

                <textarea
                  ref={mainRef}
                  value={notesMain}
                  onChange={e => { setNotesMain(e.target.value); autoGrow(e) }}
                  placeholder={'• concept\n• term = ...\n• key idea'}
                  className="w-full rounded-xl px-4 py-3 focus:outline-none text-sm resize-none leading-relaxed"
                  style={{
                    minHeight: 120,
                    backgroundColor: '#FFFFFF',
                    border: '1px solid rgba(0,0,0,0.10)',
                    color: '#1A1A1A',
                  }}
                />
              </div>
            )}

            </div>
          </div>
        )}

        {/* ── Bottom tab bar ── */}
        <div className="shrink-0 overflow-x-auto" style={{ backgroundColor: '#FFFFFF', borderTop: '1px solid rgba(0,0,0,0.07)' }}>
          <div style={{ display: 'flex', minWidth: 'fit-content' }}>
            {SESSION_TABS.map(({ id, label, num }) => {
              const isActive = activeTab === id
              const wasVisited = tabsVisited.has(id)
              return (
                <button
                  key={id}
                  onClick={() => isActive ? setActiveTab(null) : visitTab(id)}
                  style={{
                    flex: '1 1 0',
                    minWidth: 80,
                    padding: '10px 8px 8px',
                    border: 'none',
                    borderTop: isActive ? `2px solid ${dot}` : '2px solid transparent',
                    backgroundColor: 'transparent',
                    cursor: 'pointer',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    gap: 2,
                    transition: 'color 0.15s',
                    color: isActive ? dot : wasVisited && !isActive ? '#6B6B6B' : '#C0C0C0',
                  }}
                >
                  <span style={{ fontSize: 12, fontWeight: isActive ? 600 : 400, whiteSpace: 'nowrap' }}>
                    {label}
                    {wasVisited && !isActive && (
                      <span style={{ display: 'inline-block', width: 4, height: 4, borderRadius: '50%', backgroundColor: dot, marginLeft: 4, verticalAlign: 'middle', marginBottom: 1, opacity: 0.6 }} />
                    )}
                  </span>
                  <span style={{ fontSize: 10, color: isActive ? dot : '#C0C0C0', fontFamily: 'ui-monospace, monospace' }}>
                    {isActive ? 'Hide ↑' : num}
                  </span>
                </button>
              )
            })}
          </div>
        </div>

      </div>

      <style>{`
        @keyframes breathe {
          0%, 100% { transform: scale(1); }
          50% { transform: scale(1.3); }
        }
        @keyframes ringPulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.78; }
        }
        @keyframes checkPulse {
          0%, 100% { box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
          50% { box-shadow: 0 4px 16px rgba(0,0,0,0.12); }
        }
        @keyframes flashGreen {
          0%, 100% { background-color: transparent; }
          30% { background-color: rgba(16,185,129,0.08); }
        }
        @keyframes shakeRed {
          0%, 100% { transform: translateX(0); }
          20% { transform: translateX(-6px); }
          40% { transform: translateX(6px); }
          60% { transform: translateX(-4px); }
          80% { transform: translateX(4px); }
        }
      `}</style>
    </div>
  )
}
