/**
 * Shared rules for the facts guard.
 *
 * The point of this module is that every rule is derived from content/facts.json
 * rather than written out a second time here. A rule that restates a value would
 * be one more place for it to rot, which is the exact failure this is meant to stop.
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

export const facts = JSON.parse(readFileSync(join(ROOT, 'content/facts.json'), 'utf8'))

/** Files that carry marketing facts and therefore have to stay in sync. */
export const TARGET_GLOBS = [
  'public/*.html',
  'public/*.md',
  'public/llms.txt',
  'index.html',
  'signup.html',
  'app.html',
]

const money = (n) => n.toFixed(2)

/**
 * Map of our own price amounts -> the intervals they may legitimately appear with.
 *
 * Scoped to OUR amounts on purpose. The comparison pages quote competitor prices
 * (Chegg $15.95/mo, Course Hero $39.95/mo, Wolfram Alpha $7.99/mo) which are none
 * of this checker's business; flagging them produced 11 false positives on the
 * first run. What we actually care about is one of our own numbers being printed
 * against the wrong interval, which is the "$2.99/month" bug that shipped.
 *
 * Annual-equivalent figures are computed from the annual price, not hardcoded, so
 * changing a plan price updates what is accepted without editing this file.
 */
export function allowedPriceIntervals() {
  const ok = new Map()
  const allow = (amount, interval) => {
    const key = money(amount)
    if (!ok.has(key)) ok.set(key, new Set())
    ok.get(key).add(interval)
  }
  for (const plan of Object.values(facts.plans)) {
    if (plan.week) allow(plan.week, 'week')
    if (plan.month) allow(plan.month, 'month')
    if (plan.year) {
      allow(plan.year, 'year')
      allow(plan.year / 12, 'month') // "$69.99/year ($5.83/month equivalent)"
      allow(plan.year / 52, 'week')  // "works out to $1.35/week"
    }
  }
  return ok
}

const INTERVAL = { wk: 'week', week: 'week', weekly: 'week', mo: 'month', month: 'month', monthly: 'month', yr: 'year', year: 'year', annually: 'year' }

/** Plan names exactly as they appear in JSON-LD `"name"` fields, longest first. */
const PLAN_NAMES = Object.values(facts.plans).map((p) => p.name)

/**
 * A JSON-LD Offer states the amount and the billing interval in two separate
 * fields, so prose rules never see a "$2.99/month" string to object to. That is
 * precisely how 120 static pages kept advertising a retired weekly price to
 * Google for a day after the app and Stripe had both moved to monthly.
 *
 * The headline price for an Offer named after a plan is that plan's MONTHLY
 * price. Annual is expressed as its own separately named Offer ("Pro Annual").
 */
export const JSONLD_OFFER_RE = new RegExp(
  String.raw`("name":\s*"(${PLAN_NAMES.join('|')})"\s*,\s*"price":\s*")([0-9]+(?:\.[0-9]+)?)(")`,
  'g',
)

/**
 * The landing page (index.html) is hand-authored static HTML running inline
 * Babel React, so it cannot import content/facts.json at runtime without a
 * fetch on the critical path. Instead its PRICE_TABLE literal is generated
 * between markers, checked on every build, and regenerated by facts:sync.
 *
 * Same reasoning as the rest of this file: the recurrence was never caused by
 * find-and-replace being hard, it was caused by nothing reporting drift.
 */
export const PRICE_TABLE_MARKERS = {
  open: '/* facts:price-table',
  close: '/* /facts:price-table */',
}

/** Render the PRICE_TABLE literal exactly as it should appear in index.html. */
export function renderPriceTable() {
  const row = (key) => {
    const p = facts.plans[key]
    return `        ${(key + ':').padEnd(11)}{ monthly: ${p.month}, yearly: ${p.year} },`
  }
  return [
    '      const PRICE_TABLE = {',
    row('pro'),
    row('unlimited'),
    '      };',
  ].join('\n')
}

/**
 * Pull the generated region out of index.html. Returns null when the markers
 * are absent, which means someone removed them and the guard should say so
 * rather than silently passing.
 */
export function extractPriceTable(text) {
  const a = text.indexOf(PRICE_TABLE_MARKERS.open)
  if (a === -1) return null
  const afterOpen = text.indexOf('*/', a)
  if (afterOpen === -1) return null
  const b = text.indexOf(PRICE_TABLE_MARKERS.close, afterOpen)
  if (b === -1) return null
  const start = afterOpen + 2
  return { start, end: b, body: text.slice(start, b).replace(/^\n|\n\s*$/g, '') }
}

/** The monthly price an Offer with this exact plan name must advertise. */
export function expectedOfferPrice(planName) {
  const plan = Object.values(facts.plans).find((p) => p.name === planName)
  if (!plan) return null
  return plan.month === 0 ? '0' : money(plan.month)
}

/**
 * Each rule returns a list of {line, found, expected, message} problems.
 * `text` is the whole file; rules do their own line accounting so the report
 * can point at something a human can jump to.
 */
export const RULES = [
  {
    name: 'trial-length',
    // "7-day free trial", "7-day trial", "free for 7 days"
    run(text) {
      const problems = []
      const want = facts.trial.days
      const patterns = [
        /(\d+)-day free trial/gi,
        /(\d+)-day trial/gi,
        /free for (\d+) days/gi,
      ]
      for (const re of patterns) {
        for (const m of text.matchAll(re)) {
          const got = Number(m[1])
          if (got !== want) {
            problems.push({
              index: m.index,
              found: m[0],
              expected: m[0].replace(String(got), String(want)),
              message: `trial length is ${want} days (content/facts.json), found ${got}`,
            })
          }
        }
      }
      return problems
    },
  },
  {
    name: 'price-interval-pairing',
    // Catches "$2.99/month" when Pro weekly is $2.99 and Pro monthly is $9.99.
    run(text) {
      const problems = []
      const ok = allowedPriceIntervals()
      const re = /\$(\d+\.\d{2})\s*(?:\/|\s+per\s+|\s+a\s+)(wk|week|weekly|mo|month|monthly|yr|year|annually)\b/gi
      for (const m of text.matchAll(re)) {
        const amount = m[1]
        const interval = INTERVAL[m[2].toLowerCase()]
        const valid = ok.get(amount)
        // Not one of our amounts -> a competitor price on a comparison page. Skip.
        if (!valid) continue
        if (!valid.has(interval)) {
          problems.push({
            index: m.index,
            found: m[0],
            expected: null,
            message:
              `$${amount} is one of our prices but not a ${interval}ly one. ` +
              `$${amount} is valid per ${[...valid].join(' or ')}.`,
          })
        }
      }
      return problems
    },
  },
  {
    name: 'jsonld-offer-price',
    // Catches `"name": "Pro", "price": "2.99"` when Pro is $9.99/month.
    // Unambiguous, so sync-facts.mjs repairs this one automatically.
    run(text) {
      const problems = []
      for (const m of text.matchAll(JSONLD_OFFER_RE)) {
        const want = expectedOfferPrice(m[2])
        if (want === null || m[3] === want) continue
        problems.push({
          index: m.index,
          found: `"name": "${m[2]}", "price": "${m[3]}"`,
          expected: `"name": "${m[2]}", "price": "${want}"`,
          message:
            `JSON-LD offers ${m[2]} at ${m[3]} but ${m[2]} is $${want}/month ` +
            `(content/facts.json). This is the price Google shows in search results.`,
        })
      }
      return problems
    },
  },
  {
    name: 'landing-price-table',
    // Only meaningful for the file that carries the markers. Every other file
    // returns nothing, so this costs one indexOf elsewhere.
    run(text) {
      const found = extractPriceTable(text)
      if (found === null) {
        if (!text.includes(PRICE_TABLE_MARKERS.open)) return []
        return [{
          index: text.indexOf(PRICE_TABLE_MARKERS.open),
          found: 'unterminated facts:price-table region',
          expected: null,
          message: `the facts:price-table region is missing its ${PRICE_TABLE_MARKERS.close} marker`,
        }]
      }
      const want = renderPriceTable()
      if (found.body === want) return []
      return [{
        index: found.start,
        found: found.body,
        expected: want,
        message:
          'the landing page PRICE_TABLE has drifted from content/facts.json. ' +
          'Run `npm run facts:sync` to regenerate it.',
      }]
    },
  },
  {
    name: 'retired-price',
    // An amount we no longer charge, appearing anywhere customer-facing.
    //
    // This rule exists because dropping `week` from facts.plans is not enough on
    // its own: allowedPriceIntervals() only inspects amounts it recognises as
    // ours, so a retired 2.99 would be silently reclassified as a competitor
    // quote and skipped by price-interval-pairing. Not auto-fixed, because the
    // right repair depends on the sentence around it.
    run(text) {
      const problems = []
      // Offers are reported by jsonld-offer-price with a repair; skip them here
      // so one stale price is not counted twice.
      const covered = [...text.matchAll(JSONLD_OFFER_RE)].map((m) => [m.index, m.index + m[0].length])
      const isCovered = (i) => covered.some(([a, b]) => i >= a && i < b)
      for (const amount of facts.retiredPrices || []) {
        // The `$` is required. Without it this matches SVG path coordinates:
        // the inlined Google logo contains "...-.76-2.99-.76-4.59..." and both
        // of our retired amounts appear in it.
        const re = new RegExp(String.raw`\$${money(amount).replace('.', String.raw`\.`)}\b`, 'g')
        for (const m of text.matchAll(re)) {
          if (isCovered(m.index)) continue
          problems.push({
            index: m.index,
            found: m[0],
            expected: null,
            message:
              `$${money(amount)} is a retired price we no longer sell (content/facts.json ` +
              `retiredPrices). Advertising it promises a price Stripe will not honour.`,
          })
        }
      }
      return problems
    },
  },
  {
    name: 'retired-period-offer',
    // A whole JSON-LD Offer for a billing period we withdrew, e.g. "Pro Weekly".
    // Repricing it would be wrong; the offer itself has to go.
    run(text) {
      const problems = []
      const periods = (facts.retiredPeriods || []).join('|')
      if (!periods) return problems
      // Anchored to one of OUR plan names on purpose. A bare search for "weekly"
      // or "semester" inside a JSON-LD "name" matched 97 study-schedule steps
      // ("Week 8: Sharpen and rest") and FAQ entries ("What is semester GPA?"),
      // none of which are billing offers. Only "<Plan> <RetiredPeriod>" is.
      const plans = PLAN_NAMES.join('|')
      const re = new RegExp(String.raw`"name":\s*"((?:${plans})\s+(?:${periods}))"`, 'gi')
      for (const m of text.matchAll(re)) {
        problems.push({
          index: m.index,
          found: m[0],
          expected: null,
          message:
            `"${m[1]}" names a retired billing period. Remove the whole Offer block ` +
            `rather than repricing it, because we do not sell this period at all.`,
        })
      }
      return problems
    },
  },
  {
    name: 'support-email',
    run(text) {
      const problems = []
      const want = facts.support.email
      const re = /\b[\w.+-]+@getstudyedge\.com\b/g
      for (const m of text.matchAll(re)) {
        if (m[0] !== want && !/^(hello|press|legal|privacy|noreply|no-reply)@/.test(m[0])) {
          problems.push({
            index: m.index,
            found: m[0],
            expected: want,
            message: `support address is ${want} (content/facts.json)`,
          })
        }
      }
      return problems
    },
  },
]

/** Turn a character offset into a 1-indexed line number. */
export function lineOf(text, index) {
  return text.slice(0, index).split('\n').length
}
