#!/usr/bin/env node
/**
 * Point this checkout at an environment, by writing .env.local.
 *
 *   node scripts/use-env.mjs staging
 *
 * Reads ~/.studyedge/env.<name>, which lives OUTSIDE the repo and is never
 * committed, and writes .env.local, which `.env*` in .gitignore also keeps out
 * of git. Nothing secret ever lands in a tracked file.
 *
 * Why this script exists rather than "just copy the file": the app reads
 * VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY on the client, while the server
 * code and every script read SUPABASE_URL / SUPABASE_SERVICE_KEY. The source
 * file only carries the unprefixed names, so a straight copy produces an app
 * that boots with `undefined` as its Supabase URL and fails in a way that reads
 * like a code bug. This writes both spellings from one source of truth.
 *
 * It also stamps VITE_SUPABASE_EXPECTED_REF, which src/lib/supabase.js checks
 * at boot. That is what makes "I thought I was on staging" impossible to hold
 * as a belief while actually talking to production.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { homedir } from 'os'
import { join } from 'path'
import { refFromUrl, PRODUCTION_SUPABASE_REF } from './lib/envGuard.mjs'

const name = process.argv[2]
if (!name) {
  console.error('usage: node scripts/use-env.mjs <staging|...>')
  process.exit(1)
}

const src = join(homedir(), '.studyedge', `env.${name}`)
if (!existsSync(src)) {
  console.error(`No such env file: ${src}`)
  console.error('Env files live outside the repo, one per environment.')
  process.exit(1)
}

const raw = readFileSync(src, 'utf8')
const vars = {}
for (const line of raw.split('\n')) {
  const t = line.trim()
  if (!t || t.startsWith('#')) continue
  const i = t.indexOf('=')
  if (i < 0) continue
  vars[t.slice(0, i).trim()] = t.slice(i + 1).trim().replace(/^["']|["']$/g, '')
}

const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_KEY']
const missing = required.filter(k => !vars[k])
if (missing.length) {
  console.error(`${src} is missing: ${missing.join(', ')}`)
  console.error('Add them to that file. Do not substitute production values.')
  process.exit(1)
}

const ref = refFromUrl(vars.SUPABASE_URL)
if (ref === PRODUCTION_SUPABASE_REF) {
  console.error(`REFUSING: ${src} points at PRODUCTION (${ref}).`)
  console.error('This script exists to keep local runs off production. Fix the file.')
  process.exit(1)
}
if (!ref) {
  console.error(`REFUSING: could not identify a Supabase project from ${vars.SUPABASE_URL}`)
  process.exit(1)
}

// Client vars must carry the VITE_ prefix or Vite will not expose them.
const out = [
  `# Generated by scripts/use-env.mjs from ~/.studyedge/env.${name}`,
  `# Do not edit by hand and do not commit. .gitignore covers .env*`,
  '',
  `VITE_APP_ENV=${name}`,
  `VITE_SUPABASE_EXPECTED_REF=${ref}`,
  `VITE_SUPABASE_URL=${vars.SUPABASE_URL}`,
  `VITE_SUPABASE_ANON_KEY=${vars.SUPABASE_ANON_KEY}`,
  '',
  '# Server side, read by api/ handlers and by scripts/',
  `SUPABASE_URL=${vars.SUPABASE_URL}`,
  `SUPABASE_ANON_KEY=${vars.SUPABASE_ANON_KEY}`,
  `SUPABASE_SERVICE_KEY=${vars.SUPABASE_SERVICE_KEY}`,
]

// Pass through anything else the file carries, both spellings where the client
// plausibly needs it.
for (const [k, v] of Object.entries(vars)) {
  if (k.startsWith('SUPABASE_')) continue
  out.push(`${k}=${v}`)
  if (k === 'POSTHOG_API_KEY') out.push(`VITE_POSTHOG_KEY=${v}`)
  if (k === 'POSTHOG_HOST')    out.push(`VITE_POSTHOG_HOST=${v}`)
}
out.push('')

writeFileSync('.env.local', out.join('\n'))

console.log(`.env.local written from ~/.studyedge/env.${name}`)
console.log(`  environment : ${name}`)
console.log(`  project ref : ${ref}`)
console.log(`  production  : NO (production is ${PRODUCTION_SUPABASE_REF})`)
console.log('')
console.log('npm run dev will now use this. No code change required.')
